### ISSUE TITLE
Broken PHASE='-Pjruby_complete_jar_extended -Dinvoker.skip=true'

### ISSUE THREAD

**Issue by etehtsea** [jruby/jruby#4223]
I couldn't figure out how to fix this.
Introduced in 1a7d10a, 7d22b20

```
$ mvn package -B --projects '!truffle' -Dinvoker.skip=false -Pjruby_complete_jar_extended -Dinvoker.skip=true

<..>
-------------------------------------------------------
 T E S T S
-------------------------------------------------------

Results :

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0

[INFO]
[INFO] --- maven-antrun-plugin:1.7:run (jruby_complete_jar_jruby) @ jruby-tests ---
[INFO] Executing tasks

main:
     [exec] LoadError: library `java' could not be loaded: java.lang.NoClassDefFoundError: org/objectweb/asm/Opcodes
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] JRuby .............................................. SUCCESS [  0.167 s]
[INFO] JRuby Core ......................................... SUCCESS [ 17.564 s]
[INFO] JRuby Lib Setup .................................... SUCCESS [  3.270 s]
[INFO] JRuby Artifacts .................................... SUCCESS [  0.002 s]
[INFO] JRuby Complete ..................................... SUCCESS [ 10.099 s]
[INFO] JRuby Integration Tests ............................ FAILURE [  3.765 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 39.110 s
[INFO] Finished at: 2016-10-12T13:42:13+06:00
[INFO] Final Memory: 102M/1031M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.7:run (jruby_complete_jar_jruby) on project jruby-tests: An Ant BuildException has occured: exec returned: 1
[ERROR] around Ant part ...<exec failonerror="true" dir="/Users/kes/Projects/ruby/jruby/test/.." executable="java">... @ 4:91 in /Users/kes/Projects/ruby/jruby/test/target/antrun/build-main.xml
[ERROR] -> [Help 1]
<..>
```

**Comment by headius** [comment]
Yeah I'm not sure what is up either. Something wrong with how we shade the various dependencies in but it isn't clear to me what we are doing wrong. Only affects this one!

**Comment by mkristian** [comment]
I think something is missing here: https://github.com/jruby/jruby/blob/1a7d10a502fbce7cae7b391e95fd40e0b381896a/core/pom.rb#L286

at least it would be the first trial to add 'me.qmx.jitescript:jitescript'
