### PR TITLE
Fix metaclass dispatch missing meta-metaclass methods

### LINKED ISSUE #287: Class does not inherit singleton_class's class methods
I have faced a different behavior with MRI/YARV.
Is this expected?
## set up

``` ruby
class Foo
  class << self
    class << self
      def foo; end
    end
  end
end

class Bar < Foo; end

Bar.singleton_class.foo
```
## MRI/YARV

ruby 1.9.3p194 (2012-04-20 revision 35410) [i686-linux]

``` ruby
Bar.singleton_class.foo #=> nil
```
## JRuby

jruby 1.7.0.preview2 (1.9.3p203) 2012-09-03 b37a0bd on Java HotSpot(TM) Server VM 1.7.0_07-b10 [linux-i386]

``` ruby
Bar.singleton_class.foo #=> NoMethodError: undefined method `foo' for #<Class:Bar>
```

### LINKED ISSUE #6119: shopify-api gem reporting NoMethodError: undefined method `threadsafe_attribute'
shopify-api gem does not work.  Early versions used to work (a few years back).

**Environment Information**
  JRuby  9.2.11.0
  Windows 10

Easy way to reproduce:
```
gem install shopify_api
gem install shopify_api_console
shopify-api console
```

```
NoMethodError: undefined method `threadsafe_attribute' for #<Class:ShopifyAPI::Base>
       method_missing at org/jruby/RubyBasicObject.java:1708
      singleton class at C:/jruby-9.2.11.0/lib/ruby/gems/shared/gems/shopify_api-9.0.2/lib/shopify_api/resources/base.rb:34
         <class:Base> at C:/jruby-9.2.11.0/lib/ruby/gems/shared/gems/shopify_api-9.0.2/lib/shopify_api/resources/base.rb:33
  <module:ShopifyAPI> at C:/jruby-9.2.11.0/lib/ruby/gems/shared/gems/shopify_api-9.0.2/lib/shopify_api/resources/base.rb:4
               <main> at C:/jruby-9.2.11.0/lib/ruby/gems/shared/gems/shopify_api-9.0.2/lib/shopify_api/resources/base.rb:3
              require at org/jruby/RubyKernel.java:974
              require at C:/jruby-9.2.11.0/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:54
               <main> at C:/jruby-9.2.11.0/lib/ruby/gems/shared/gems/shopify_api-9.0.2/lib/shopify_api/resources.rb:1
              require at org/jruby/RubyKernel.java:974
              require at C:/jruby-9.2.11.0/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:54
               <main> at C:/jruby-9.2.11.0/lib/ruby/gems/shared/gems/shopify_api-9.0.2/lib/shopify_api.rb:21
              require at org/jruby/RubyKernel.java:974
              require at C:/jruby-9.2.11.0/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:54
               <main> at C:/jruby-9.2.11.0/lib/ruby/gems/shared/gems/shopify_api_console-2.0.0/lib/shopify_api_console/console.rb:4
              require at org/jruby/RubyKernel.java:974
              require at C:/jruby-9.2.11.0/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:54
               <main> at C:/jruby-9.2.11.0/lib/ruby/gems/shared/gems/shopify_api_console-2.0.0/bin/shopify-api:3
                 load at org/jruby/RubyKernel.java:1009
               <main> at C:\jruby-9.2.11.0\bin\shopify-api:23
```

Works fine with normal ruby-2.5.7-1-x64 from https://www.ruby-lang.org

### PR DESCRIPTION
**Pull request by sampokuokkanen**
The sample code from https://github.com/jruby/jruby/issues/287 still errors on JRuby master: 

```ruby
class Foo
  class << self
    class << self
      def foo; end
    end
  end
end
class Bar < Foo; end
Bar.singleton_class.foo
(irb):11:in 'evaluate': undefined method 'foo' for class #<Class:Bar> (NoMethodError)
```

This is because currently in master the code is stripping away singleton classes and not creating a singleton class in case one is missing. 

So skip the wrapper with `isIncluded()` and use `singletonClass(context)` to get the correct eigenclass. 
This lets us drop `spec/tags/ruby/language/metaclass_tags.txt`, but the MRI tests are still failing since they go one step further (meta-meta-meta tier, blows up on line 160), and with meta-meta classes there is still an issue there with how they are handled (see MetaClass.java:109, can't just fix it as it leads to a stack overflow with the same shape of fix as I did on line 542)

### CODE REVIEW

File: core/src/main/java/org/jruby/RubyBasicObject.java [hunk 1]
```diff
@@ -538,7 +538,9 @@ public RubyClass makeMetaClass(ThreadContext context, RubyClass superClass) {
         MetaClass klass = new MetaClass(context.runtime, superClass, this); // rb_class_boot
         setMetaClass(klass);
 
-        klass.setMetaClass(superClass.getRealClass().metaClass);
+        // MRI: SET_METACLASS_OF(metaclass, ENSURE_EIGENCLASS(tmp))
+        RubyClass effectiveSuper = superClass.isIncluded() ? superClass.getRealClass() : superClass;
```
Comment (kares) [inline core/src/main/java/org/jruby/RubyBasicObject.java:542]: not sure I follow, is the included check really needed?

Comment (sampokuokkanen) [reply core/src/main/java/org/jruby/RubyBasicObject.java:542]: While writing this I first thought we wouldn't need the check, but the code didn't work without it. Turns out we can get a BlankSlateWrapper here instead of the actual module (from JavaPackage.createJavaPackageClass).

Should I add `// unwrap IncludedModuleWrapper (e.g. BlankSlateWrapper from JavaPackage)` as an inline comment?

Comment (sampokuokkanen) [reply core/src/main/java/org/jruby/RubyBasicObject.java:542]: Without it on boot: 
`java.lang.UnsupportedOperationException: An included class is only a wrapper for a module`

**Review by headius — APPROVED** [review]
Aha, I think I understand after looking at the code.

An object's singleton class's metaclass should be the singleton class of the object's class's superclass. When the object's class has included a module, the module's singleton class should be used.

The old logic simply used the superclass's (or supermodule's) metaclass without acquiring its singleton class. This resulted in future method lookups traversing the metaclass hierarchy rather than the singleton class hierarchy.

It's a complicated system but this seems more correct. I'm sure there's other tags and specs passing now because of this.

**Comment by headius** [comment]
I hoped it might fix https://github.com/jruby/jruby/issues/7787 but it does not. Perhaps another challenge?

**Comment by sampokuokkanen** [comment]
Thanks, I'll look into https://github.com/jruby/jruby/issues/7787.

**Comment by headius** [comment]
Appears to also fix #6119.

**Comment by headius** [comment]
My searching did not find any other issues, but I did not audit all tagged tests/specs (it's a hard thing to search for when some of the failures are due to methods being missing on singleton classes!) and I still feel like there have been other issues related to incorrect singleton class hierarchies.

Nevertheless I think we'll proceed with this since it fixes at least two known issues, one of which was silently closed long ago.
