### ISSUE TITLE
Constant becomes nil when running ScriptEngine with transient/persistent local variables.

### ISSUE THREAD

**Issue by dmac100** [jruby/jruby#4720]
### Environment

jruby-complete-9.1.6.0.jar and current master
Windows 7 and Linux
Java 1.8.0_131 Oracle JDK 64 bit

### Expected Behavior

With:

    System.setProperty("org.jruby.embed.localvariable.behavior", "transient");
    // or System.setProperty("org.jruby.embed.localvariable.behavior", "persistent");

    ScriptEngine engine = new ScriptEngineManager().getEngineByName("jruby");
    engine.eval("require 'date'");
    engine.eval("Date.new");
    engine.eval("require 'date'");
    engine.eval("Date.new");

this should produce nothing.

### Actual Behavior

Throws exception:

    NoMethodError: undefined method `>' for nil:NilClass
       civil at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/date.rb:829
      <main> at <script>:1
    Exception in thread "main" javax.script.ScriptException: org.jruby.embed.EvalFailedException: (NoMethodError) undefined method `>' for nil:NilClass
        at org.jruby.embed.jsr223.JRubyEngine.wrapException(JRubyEngine.java:104)
        at org.jruby.embed.jsr223.JRubyEngine.eval(JRubyEngine.java:93)
        at org.jruby.embed.jsr223.JRubyEngine.eval(JRubyEngine.java:142)
        at Main.main(Main.java:13)
    Caused by: org.jruby.embed.EvalFailedException: (NoMethodError) undefined method `>' for nil:NilClass
        at org.jruby.embed.internal.EmbedEvalUnitImpl.run(EmbedEvalUnitImpl.java:131)
        at org.jruby.embed.jsr223.JRubyEngine.eval(JRubyEngine.java:90)
        ... 2 more
    Caused by: org.jruby.exceptions.RaiseException: (NoMethodError) undefined method `>' for nil:NilClass
        at RUBY.civil(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/date.rb:829)
        at RUBY.<main>(<script>:1)

Replacing date.rb with:

    class Date
        ABC = 2

        def initialize
            puts "ABC: #{ABC.nil?}"
        end
    end

Shows that the constant ABC becomes nil the second time `Date.new` is run. This is fine if the constant is named 'A' though.

**Comment by kares** [comment]
confirmed that this is working in 9.2.0, please note that 9.2 switched local variable behavior to PERSISTENT
