### ISSUE TITLE
NoSuchMethodError when a Ruby subclass of a Java class includes a module

### ISSUE THREAD

**Issue by yamam** [jruby/jruby#9655]
## Environment

- JRuby: `jruby 10.1.2.0-SNAPSHOT (4.0.0) 2026-09-08 d6eb6862bb`
- Java: OpenJDK 25.0.4
- OS: Ubuntu Linux x86_64

## Reproduction

Save the following as `repro.rb`:

```ruby
class ReproChild < java.lang.Object
  include Enumerable

  def initialize
    super
  end
end

ReproChild.new
```

Run:

```bash
jruby repro.rb
```

## Actual behavior

JRuby raises `NoSuchMethodError` while creating `ReproChild`:

```
Unhandled Java exception: java.lang.NoSuchMethodError: 'org.jruby.exceptions.RaiseException org.jruby.Ruby.newNoMethodError(java.lang.String, java.lang.String, org.jruby.runtime.builtin.IRubyObject[])'
java.lang.NoSuchMethodError: 'org.jruby.exceptions.RaiseException org.jruby.Ruby.newNoMethodError(java.lang.String, java.lang.String, org.jruby.runtime.builtin.IRubyObject[])'
               <init> at rubyobj/repro.rb:3
               <init> at rubyobj/repro.rb:3
                 call at org/jruby/java/proxies/ConcreteJavaProxy.java:312
                 call at org/jruby/java/proxies/ConcreteJavaProxy.java:170
  performIndirectCall at org/jruby/ir/targets/indy/InvokeSite.java:893
               invoke at org/jruby/ir/targets/indy/InvokeSite.java:797
            ❤ script at repro.rb:7
                  run at repro.rb:-1
  invokeWithArguments at java/lang/invoke/MethodHandle.java:735
                 load at org/jruby/ir/Compiler.java:114
            runScript at org/jruby/Ruby.java:1227
          runNormally at org/jruby/Ruby.java:1139
          runFromMain at org/jruby/Ruby.java:984
          internalRun at org/jruby/main/Main.java:289
                  run at org/jruby/main/Main.java:239
                 main at org/jruby/main/Main.java:211

```

## Expected behavior

`ReproChild.new` should complete without an exception.

## Additional information

The error appears to come from a generated Java constructor attempting to call `Ruby.newNoMethodError(String, String, IRubyObject[])`, although the available overload has a different third-argument type. This may be related to the Java subclass reification changes in commit e5a8dc10d4 (#9557).

**Comment by chadlwilson** [comment]
Looks kinda like two issues here? Perhaps one, the root problem with the module definition (pre-java-constructor code?) and then another issue with actually creating a correct exception? (NoSuchMethodError trying to create a no method error is weird?)

Marked for 10.1.2 review for now as seems a possible regression in currently unreleased code.

**Comment by kares** [comment]
seems like a Java integration issue, confirmed it's caused by https://github.com/jruby/jruby/pull/9557 although the signature for calling the method seems to have not changed, will investigate further and propose a fix.

**Comment by kares** [comment]
I agree there's potentially 2 issues:
- super detection needs to treat included-module ancestry (smt I completely ignored in #9557)
- the error fallback then needs to use the proper API (a pre-existing bug although never triggered)

**Comment by headius** [comment]
We'll need to fix this regression or roll back #9557 before releasing 10.1.2.0.

@yamam Thanks for the quick report... I'm glad to see you are testing against jruby-head!
