### ISSUE TITLE
NoMethodError for Concurrent::Hash#deep_merge!

### ISSUE THREAD

**Issue by mohamedhafez** [jruby/jruby#6547]
In JRuby version 9.2.14.0 `Concurrent::Hash#deep_merge!` is undefined, but it is defined for ~~Ruby 2.6.6~~ Ruby 2.5.8. This is causing an error in my Rails app when upgrading to version 1.8.8 of the `i18n` gem, which uses the method (see https://github.com/ruby-i18n/i18n/issues/554)

```
NoMethodError: undefined method `deep_merge!' for {}:Concurrent::Hash
Did you mean?  deep_merge
                      store_translations at /Users/mohamed/.rvm/gems/jruby-9.2.14.0/gems/i18n-1.8.8/lib/i18n/backend/simple.rb:45
                               load_file at /Users/mohamed/.rvm/gems/jruby-9.2.14.0/gems/i18n-1.8.8/lib/i18n/backend/base.rb:230
                                    each at org/jruby/RubyHash.java:1415
                               load_file at /Users/mohamed/.rvm/gems/jruby-9.2.14.0/gems/i18n-1.8.8/lib/i18n/backend/base.rb:230
                       load_translations at /Users/mohamed/.rvm/gems/jruby-9.2.14.0/gems/i18n-1.8.8/lib/i18n/backend/base.rb:18
                                    each at org/jruby/RubyArray.java:1809
                       load_translations at /Users/mohamed/.rvm/gems/jruby-9.2.14.0/gems/i18n-1.8.8/lib/i18n/backend/base.rb:18
                       init_translations at /Users/mohamed/.rvm/gems/jruby-9.2.14.0/gems/i18n-1.8.8/lib/i18n/backend/simple.rb:80
                             eager_load! at /Users/mohamed/.rvm/gems/jruby-9.2.14.0/gems/i18n-1.8.8/lib/i18n/backend/simple.rb:65
                             eager_load! at /Users/mohamed/.rvm/gems/jruby-9.2.14.0/gems/i18n-1.8.8/lib/i18n.rb:77
                                    each at org/jruby/RubyArray.java:1809
                                Finisher at /Users/mohamed/.rvm/gems/jruby-9.2.14.0/gems/railties-6.0.3.4/lib/rails/application/finisher.rb:123
                           instance_exec at org/jruby/RubyBasicObject.java:2694
                                     run at /Users/mohamed/.rvm/gems/jruby-9.2.14.0/gems/railties-6.0.3.4/lib/rails/initializable.rb:32
                        run_initializers at /Users/mohamed/.rvm/gems/jruby-9.2.14.0/gems/railties-6.0.3.4/lib/rails/initializable.rb:61
                              tsort_each at /Users/mohamed/.rvm/rubies/jruby-9.2.14.0/lib/ruby/stdlib/tsort.rb:228
       each_strongly_connected_component at /Users/mohamed/.rvm/rubies/jruby-9.2.14.0/lib/ruby/stdlib/tsort.rb:350
  each_strongly_connected_component_from at /Users/mohamed/.rvm/rubies/jruby-9.2.14.0/lib/ruby/stdlib/tsort.rb:431
       each_strongly_connected_component at /Users/mohamed/.rvm/rubies/jruby-9.2.14.0/lib/ruby/stdlib/tsort.rb:349
                                    each at org/jruby/RubyArray.java:1809
                                    call at org/jruby/RubyMethod.java:131
       each_strongly_connected_component at /Users/mohamed/.rvm/rubies/jruby-9.2.14.0/lib/ruby/stdlib/tsort.rb:347
                              tsort_each at /Users/mohamed/.rvm/rubies/jruby-9.2.14.0/lib/ruby/stdlib/tsort.rb:226
                              tsort_each at /Users/mohamed/.rvm/rubies/jruby-9.2.14.0/lib/ruby/stdlib/tsort.rb:205
                        run_initializers at /Users/mohamed/.rvm/gems/jruby-9.2.14.0/gems/railties-6.0.3.4/lib/rails/initializable.rb:60
                             initialize! at /Users/mohamed/.rvm/gems/jruby-9.2.14.0/gems/railties-6.0.3.4/lib/rails/application.rb:363
                                  <main> at /Users/mohamed/rubyprojects/substitutealert/config/environment.rb:33
                                 require at org/jruby/RubyKernel.java:974
                                 require at /Users/mohamed/.rvm/gems/jruby-9.2.14.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324
                         load_dependency at /Users/mohamed/.rvm/gems/jruby-9.2.14.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:291
                                 require at /Users/mohamed/.rvm/gems/jruby-9.2.14.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324
                    require_environment! at /Users/mohamed/.rvm/gems/jruby-9.2.14.0/gems/railties-6.0.3.4/lib/rails/application.rb:339
                    require_environment! at /Users/mohamed/.rvm/gems/jruby-9.2.14.0/gems/railties-6.0.3.4/lib/rails/command/actions.rb:28
    require_application_and_environment! at /Users/mohamed/.rvm/gems/jruby-9.2.14.0/gems/railties-6.0.3.4/lib/rails/command/actions.rb:15
                                 perform at /Users/mohamed/.rvm/gems/jruby-9.2.14.0/gems/railties-6.0.3.4/lib/rails/commands/console/console_command.rb:101
                                     run at /Users/mohamed/.rvm/gems/jruby-9.2.14.0/gems/thor-1.1.0/lib/thor/command.rb:27
                          invoke_command at /Users/mohamed/.rvm/gems/jruby-9.2.14.0/gems/thor-1.1.0/lib/thor/invocation.rb:127
                                dispatch at /Users/mohamed/.rvm/gems/jruby-9.2.14.0/gems/thor-1.1.0/lib/thor.rb:392
                                 perform at /Users/mohamed/.rvm/gems/jruby-9.2.14.0/gems/railties-6.0.3.4/lib/rails/command/base.rb:69
                                  invoke at /Users/mohamed/.rvm/gems/jruby-9.2.14.0/gems/railties-6.0.3.4/lib/rails/command.rb:46
                                  <main> at /Users/mohamed/.rvm/gems/jruby-9.2.14.0/gems/railties-6.0.3.4/lib/rails/commands.rb:18
                                 require at org/jruby/RubyKernel.java:974
                                  <main> at /Users/mohamed/rubyprojects/substitutealert/bin/rails:4
```

**Comment by ahorek** [comment]
_it is defined for Ruby 2.6.6_ - no, it's defined by rails or i18n using refinements

https://github.com/ruby-i18n/i18n/blob/master/lib/i18n/core_ext/hash.rb
https://github.com/rails/rails/blob/main/activesupport/lib/active_support/core_ext/hash/deep_merge.rb#L23

it seems to work on JRuby 9.3.0.0, @mohamedhafez could you confirm it?

**Comment by DmitryTsepelev** [comment]
I've just got some failing [specs](https://github.com/DmitryTsepelev/store_model/runs/1813690691?check_suite_focus=true) in my gem with this error (specs are run every day, everything was fine yesterday).

**Comment by mohamedhafez** [comment]
Gah my mistake for comparing 9.2.14.0 to Ruby 2.6, obviously that's only compatible with Ruby 2.5. Nevertheless, the following works without issue in MRI Ruby 2.5.8, but gives a `NoMethodError` for JRuby 9.2.14.0 *and* 9.3.0.0 (as built from the master branch):

1) use `rails new` to generate a new rails project (I'm using rails 6.0.3.4)
2) run `rails console`
3) type in `Concurrent::Hash.new.deep_merge!({})`

But you know what's really weird? For both 9.2.14.0 and 9.3.0.0, if instead of running `rails console`, you just run `irb` and then `require 'rails`', then it works... 🤷

**Comment by headius** [comment]
Could be a bug in refinements that is fixed on master. I will try to reproduce.

**Comment by headius** [comment]
I can reproduce at a command line:

```
$ jruby -ri18n -e 'Concurrent::Hash.new.deep_merge!({})'
NoMethodError: undefined method `deep_merge!' for {}:Concurrent::Hash
  <main> at -e:1
```

However CRuby seems to behave the same:

```
$ rvm ruby-2.6.5 do ruby -ri18n -e 'Concurrent::Hash.new.deep_merge!({})'
Traceback (most recent call last):
-e:1:in `<main>': undefined method `deep_merge!' for {}:Concurrent::Hash (NoMethodError)
```

**Comment by headius** [comment]
If I load the appropriate sources and use the refinement, it works ok:

```
$ jruby -ri18n -ri18n/core_ext/hash -e 'using I18n::HashRefinements; p Concurrent::Hash.new.deep_merge!({})'
{}
```

**Comment by headius** [comment]
The following script by @ahorek appears to reproduce the issue correctly:

```ruby
require 'i18n/core_ext/hash'
require 'active_support/core_ext/hash/deep_merge'
require 'concurrent'

Concurrent::Hash.new.deep_merge!({})
```

Removing the i18n require fixes it, and my examples above work because they use the i18n refinement in isolation. It seems the combination of ActiveSupport defining a normal `deep_merge!` and i18n defining a refined version are triggering this.

Refinements work by inserting a tag into the original class's method table for a given method name, and this tag then is used to indicate that a refined method search should be performed. I suspect that the i18n refinement is causing the ActiveSupport method to get wiped out or otherwise hidden.

**Comment by headius** [comment]
Ok I think I know the problem.

It is a combination of a normal method, a refined method, and the Synchronized module that JRuby provides to force all methods to use synchronization.

The issue is that our Synchronized logic wraps all method lookups with a synchronized DynamicMethod wrapper, which prevents any refined entries from getting unwrapped. We still see that the method is refined, go into the logic to look for a refinement, see none active, and proceed to try to unwrap... but the unwrap logic only knows about RefinedWrapper.

This is tricky to solve and shows a flaw in the now-ancient Synchronized wrapper. Another mechanism for forcing class-wide synchronization may be needed.

**Comment by headius** [comment]
I looked into why this doesn't affect other implementations, and it is largely because they do not support the same degree of synchronization that our Synchronized module triggers.

* In JRuby, all methods looked up from a Synchronized class will be wrapped in synchronization, even methods that are added later. We do this by hooking into the lookup process and wrapping them lazily as they are retrieved.
* In CRuby, no synchronization happens out of a false believe that the GVL will protect users from concurrent modification.
* In TruffleRuby, the equivalent to our Synchronized module will wrap methods eagerly, and only affect methods on the target class that are defined at that point. Future methods or redefined methods will lose synchronization unless it is applied again.

Clearly there are problems with each approach, but only the JRuby approach interferes with the additional wrapping mechanisms that refinements depend upon.

cc @pitr-ch for some discussion about how better to handle this.

**Comment by headius** [comment]
Also cc @kares since he has worked on custom CacheEntry logic for fixnums in the past and may be have some insight into this. I am considering moving the synchronization logic to the cache entry, with two ways to get the method out: get raw, and get wrapped. Metaprogramming would use get raw since the wrapper is only intended to be used for invocation. That would avoid search logic getting tripper up by wrappers, and then eventually we go to invocation and get the wrapped version.

**Comment by headius** [comment]
Here is a short-term fix that appears to get this case working, but there is a larger systemic issue with these not-competely-transparent delegating wrappers (just used for synchronization and profiling right now):

```diff
diff --git a/core/src/main/java/org/jruby/RubyModule.java b/core/src/main/java/org/jruby/RubyModule.java
index 1b72bebfc5..4c3647c251 100644
--- a/core/src/main/java/org/jruby/RubyModule.java
+++ b/core/src/main/java/org/jruby/RubyModule.java
@@ -75,6 +75,7 @@ import org.jruby.internal.runtime.methods.AliasMethod;
 import org.jruby.internal.runtime.methods.AttrReaderMethod;
 import org.jruby.internal.runtime.methods.AttrWriterMethod;
 import org.jruby.internal.runtime.methods.DefineMethodMethod;
+import org.jruby.internal.runtime.methods.DelegatingDynamicMethod;
 import org.jruby.internal.runtime.methods.DynamicMethod;
 import org.jruby.internal.runtime.methods.JavaMethod;
 import org.jruby.internal.runtime.methods.NativeCallMethod;
@@ -1535,6 +1536,11 @@ public class RubyModule extends RubyObject {
 
         DynamicMethod method = entry.method;
 
+        // unwrap delegated methods so we can see them properly
+        if (method instanceof DelegatingDynamicMethod) {
+            method = ((DelegatingDynamicMethod) method).getDelegate();
+        }
+
         if (method instanceof RefinedWrapper){
             // original without refined flag
             return cacheEntryFactory.newCacheEntry(id, ((RefinedWrapper) method).getWrapped(), entry.sourceModule, entry.token);
```

Basically we would need to audit all logic that uses method entries to ensure they are using the delegate appropriately. Or we need to instead customize the cache entry to know about the two use cases of metaprogramming versus invocation and provide the raw or wrapped version.

**Comment by radar** [comment]
Is there anything we could be doing in i18n itself to stop this from being a problem?

**Comment by headius** [comment]
@radar Thank you for reaching out!

The simplest fix would be to remove the refinements on `Concurrent::Hash` and just add the methods directly, or define them as utility functions elsewhere and pass in the two hashes to merge (like `MyUtil.deep_merge!(hash_a, hash_b)`).

The basic issue (described in more detail above) is that the JRuby `Synchronized` logic, used to make `Concurrent::Hash` trivially threadsafe, is incompatible with refinements as of JRuby 9.2.14.0. So using either is fine, but using them together leads to improper handling of the class's method table.

This is definitely a bug we need to fix in `Synchronized` but in the interest of getting people running again I think avoiding refinement against Concurrent::Hash is the best short-term option.

**Comment by jlahtinen** [comment]
I was debugging this and thinked to open an issue (then found this). Seems like autoloading and prepending works differently with curby and jruby.

a.rb

    module Foo
      # autoload :HashRefinements, 'b' # if required, all ok
      autoload :Bar, 'b' # if required, all ok
    end
    
    Hash.prepend Module.new # without this all ok
    Foo::Bar.new.something

b.rb

    require 'concurrent/hash'
    
    module Foo
      # if this is moved to required file, all ok
      module HashRefinements
        refine Hash do
          def important; end
        end
      end
    
      # or this ir moved to required file, all ok
      class Bar
        using Foo::HashRefinements
    
        def something
          Concurrent::Hash.new.important
        end
      end
    end

Running a.rb with cruby `ruby -I '.' a.rb` works but not with jruby 9.2.13.0.

**Comment by jlahtinen** [comment]
Requiring i18n/backend/simple before requiring rails in application.rb "fixes" this with puma. Does not help when running with jruby-rack and tomcat.

**Comment by headius** [comment]
@jlahtinen I think your case may be a slightly different issue. The root cause for this issue is that an existing method on Concurrent::Hash gets refined and the internal logic to handle refined versions of existing methods breaks due to how Concurrent::Hash uses the JRuby Synchronized module. It is very specifically the combination of these three things:

* Target class uses Synchronized to become threadsafe
* Target class has a method X
* Refinement of target class also has a method X

You say that loading i18n/backend/simple "fixes" this... does that refer to this issue or the example you found with prepends and refinements?

**Comment by headius** [comment]
I should also clarify... the example from @jlahtinen above misses two of the triggers for this issue because:

* it does not refine Concurrent::Hash directly
* it does not refine an existing method

This is why I believe it is a separate but possibly related issue.

**Comment by jlahtinen** [comment]
> You say that loading i18n/backend/simple "fixes" this... does that refer to this issue or the example you found with prepends and refinements?

Mainly to this issue. My example also works if eveything is required (or in same file) not autoloaded.

**Comment by mount986** [comment]
Our organization uses the Faker gem extensively for automation testing using jruby, and we've been seeing the same error, as it uses i18n for much of it's functionality.  I can confirm that by adding a require for `i18n/backend/simple` it was able to get us back up and running.  Not a permanent fix, but definitely a good temporary workaround.. I also had to require `i18n/backend` first to meet dependencies for the simple module:
```
require 'i18n/backend'
require 'i18n/backend/simple'
require 'active_support'
require 'active_support/core_ext'
require 'factory_bot'
require 'faker'
```

**Comment by headius** [comment]
Glad to hear that the workaround of `require 'i18n/backend/simple` early is getting people past this.

I do not have any other fixes to land for this at the moment. The larger changes to Synchronized and the profiling wrappers will need to happen separately and probably won't go into 9.2. I will land my other change shortly... can y'all verify `jruby-9.2' branch HEAD or one of the snapshot builds that it produces?

**Comment by headius** [comment]
The one-off fix has landed. I will look into the more elaborate fix soon.

**Comment by mount986** [comment]
I built branch jruby-9.2 and commented out the requires for i18n and my tests passed 👍
