### ISSUE TITLE
Regression: multiple refinements of the same class

### ISSUE THREAD

**Issue by palkan** [jruby/jruby#5550]
### Environment

* JRuby version: `jruby 9.2.5.0 (2.5.0) 2018-12-06 6d5a228 OpenJDK 64-Bit Server VM 25.181-b13 on 1.8.0_181-8u181-b13-2~deb9u1-b13 +jit [linux-x86_64]`

### Expected Behavior

Given the code below:

```ruby
class A
  def foo
    puts "foo"
    self
  end
end

using(Module.new do
  refine A do
    def baz
      puts "bar"
      self
    end
  end
end)

using(Module.new do
  refine A do
    def bar
      puts "bar"
      self
    end
  end
end)

begin
  A.new.foo.baz.bar
rescue => e
  p e.message
end

begin
  A.new.foo.bar.baz
rescue => e
  p e.message
end
```

I expect it to print:

```
"foo"
"baz"
"bar"
"foo"
"bar"
"baz"
```

The code below worked in 9.1.7.0 (just checked: broken since 9.2.0.0).

### Actual Behavior

It prints exceptions:

```
"foo"
"undefined method `baz' for #<A:0x1c3a4799>"
"foo"
"bar"
"undefined method `baz' for #<A:0x3043fe0e>"
```

If I change the order of `using`, the `bar` method becomes undefined; hence only the last added refinement for the class is activated.

**Comment by headius** [comment]
Fixed once #5627 lands.

Note that MRI 2.5 does not match your expected output, but does match JRuby output after #5627:

```
[] ~/projects/jruby $ jruby blah.rb
foo
bar
bar
foo
bar
bar

[] ~/projects/jruby $ rvm ruby-2.5.3 do ruby blah.rb
foo
bar
bar
foo
bar
bar
```

If you have some other expectation we should dig into that...but otherwise we're going to call this fixed since it matches MRI.

**Comment by palkan** [comment]
> Note that MRI 2.5 does not match your expected output, but does match JRuby output after
> If you have some other expectation we should dig into that

Sorry, there is a typo in the example script from the PR description.
So, it should be fixed.

Thanks!

**Comment by headius** [comment]
Fixed for 9.2.7 (note this output differs from description due to a typo by @palkan):

```
[] ~/projects/jruby $ cat blah.rb
class A
  def foo
    puts "foo"
    self
  end
end

using(Module.new do
  refine A do
    def baz
      puts "bar"
      self
    end
  end
end)

using(Module.new do
  refine A do
    def bar
      puts "bar"
      self
    end
  end
end)

begin
  A.new.foo.baz.bar
rescue => e
  p e.message
end

begin
  A.new.foo.bar.baz
rescue => e
  p e.message
end
[] ~/projects/jruby $ rvm ruby-2.5.3 do ruby blah.rb
foo
bar
bar
foo
bar
bar

[] ~/projects/jruby $ jruby -v blah.rb
jruby 9.2.7.0-SNAPSHOT (2.5.3) 2019-04-08 2122e9f OpenJDK 64-Bit Server VM 25.202-b08 on 1.8.0_202-b08 +jit [darwin-x86_64]
foo
bar
bar
foo
bar
bar
```
