### ISSUE TITLE
Class does not inherit singleton_class's class methods

### ISSUE THREAD

**Issue by kachick** [jruby/jruby#287]
I have faced a different behavior with MRI/YARV.
Is this expected?
## set up

``` ruby
class Foo
  class << self
    class << self
      def foo; end
    end
  end
end

class Bar < Foo; end

Bar.singleton_class.foo
```
## MRI/YARV

ruby 1.9.3p194 (2012-04-20 revision 35410) [i686-linux]

``` ruby
Bar.singleton_class.foo #=> nil
```
## JRuby

jruby 1.7.0.preview2 (1.9.3p203) 2012-09-03 b37a0bd on Java HotSpot(TM) Server VM 1.7.0_07-b10 [linux-i386]

``` ruby
Bar.singleton_class.foo #=> NoMethodError: undefined method `foo' for #<Class:Bar>
```

**Comment by rjnienaber** [comment]
This still seems to be an issue in JRuby 1.7.20 and JRuby HEAD:

```
----------
ruby 1.9.3p551 (2014-11-13 revision 48407) [x86_64-darwin14.0.0]
nil
----------
jruby 1.7.20 (1.9.3p551) 2015-05-04 3086e6a on Java HotSpot(TM) 64-Bit Server VM 1.8.0_05-b13 +jit [darwin-x86_64]
NoMethodError: undefined method `foo' for #<Class:Bar>
  (root) at /tmp/test.rb:11
==========
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]
nil
----------
jruby 9.0.0.0-SNAPSHOT (2.2.2) 2015-05-05 c0d9bc3 Java HotSpot(TM) 64-Bit Server VM 25.5-b02 on 1.8.0_05-b13 +jit [darwin-x86_64]
NoMethodError: undefined method `foo' for #<Class:Bar>
  method_missing at org/jruby/RubyBasicObject.java:1606
           <top> at /tmp/test.rb:11
----------
```

**Comment by rcrews** [comment]
Just ran the above test case with 9.1.16.0. Can this be closed?
```
15:48:59 ~ 🐾  irb
jruby-9.1.16.0 :001 > class Foo
jruby-9.1.16.0 :002?>     class << self
jruby-9.1.16.0 :003?>         class << self
jruby-9.1.16.0 :004?>             def foo; end
jruby-9.1.16.0 :005?>           end
jruby-9.1.16.0 :006?>       end
jruby-9.1.16.0 :007?>   end
 => :foo 
jruby-9.1.16.0 :008 >   class Bar < Foo; end
 => nil 
```

**Comment by kares** [comment]
closing - especially since it was reported against 1.7 which is EOL. thanks @rcrews

**Comment by prashantvithani** [comment]
@kares This issue still persists in 9.2.0.0
```
jruby-9.2.0.0 :015 > class Foo
jruby-9.2.0.0 :016?>     class << self
jruby-9.2.0.0 :017?>         class << self
jruby-9.2.0.0 :018?>             def foo; end
jruby-9.2.0.0 :019?>           end
jruby-9.2.0.0 :020?>       end
jruby-9.2.0.0 :021?>   end
 => :foo 
jruby-9.2.0.0 :022 > 
jruby-9.2.0.0 :023 > class Bar < Foo; end
 => nil 
jruby-9.2.0.0 :024 > Foo.singleton_class.foo
 => nil 
jruby-9.2.0.0 :025 > Bar.singleton_class.foo
Traceback (most recent call last):
        7: from /Users/prvithani/.rvm/rubies/jruby-9.2.0.0/bin/irb:13:in `<main>'
        6: from org/jruby/RubyKernel.java:1180:in `catch'
        5: from org/jruby/RubyKernel.java:1180:in `catch'
        4: from org/jruby/RubyKernel.java:1418:in `loop'
        3: from org/jruby/RubyKernel.java:1037:in `eval'
        2: from (irb):25:in `<eval>'
        1: from org/jruby/RubyBasicObject.java:1720:in `method_missing'
NoMethodError (undefined method `foo' for #<Class:Bar>)
jruby-9.2.0.0 :026 > 
```

**Comment by headius** [comment]
This appears to be working in 9.2.1.0. I'm trying to confirm what commit fixed it.

**Comment by headius** [comment]
Nevermind...I forgot the original script does not include the failing line. I'll edit it so we don't make the same mistake.

**Comment by headius** [comment]
Never actually fixed; accidentally closed but never reopened until now.

**Comment by headius** [comment]
Fixed by #9446.
