### ISSUE TITLE
org.jruby.javasupport.JavaClass.getMethods generates NoMethodError

### ISSUE THREAD

**Issue by CeesZ** [jruby/jruby#3239]
I tried to upgrade an existing program to work with jruby-complete-1.7.21.jar.
The program halts with an error:
NomethodError: undefined method 'getMethods' for #<Class:03259fa>
Looking up the code, it concerns the following call:
org.jruby.javasupport.JavaClass.getMethods(qtclass)
p [qtclass, qtclass.class]  #=> [Java::ComTrolltechQt::QtInfo, Class]
Further checking shows this code works in 1.7.19 but also fails in 1.7.20.1

Is this method now obsolete or can this be due to a bug?

**Comment by kares** [comment]
@CeesZ seems like a regression, could we have your full back/stack trace please?
... also are you doing `org.jruby.javasupport.JavaClass.getMethods(qtclass)` from Ruby or Java?

**Comment by CeesZ** [comment]
Thanks for looking at this. The call is made from a Ruby program. Following are two back traces; the first one if I run the program from a jar based on jruby-complete, and the second one if I run it directly using the jruby compiler. They both generate the same error and essentially generate the same back trace.


(stack, running from a jar based on jruby-complete-1.7.21)
NoMethodError: undefined method `getMethods' for #<Class:0x7a356>
  setup_qt_signals at /C:/Program Files (x86)/XLibriz/lib/java/XLibriz.jar!/lib/ruby/qt_connect-1.6.1/lib/qt_connect/qt_jbindings.rb:341
     const_missing at /C:/Program Files (x86)/XLibriz/lib/java/XLibriz.jar!/lib/ruby/qt_connect-1.6.1/lib/qt_connect/qt_jbindings.rb:323
                Qt at /C:/Program Files (x86)/XLibriz/lib/java/XLibriz.jar!/lib/ruby/qt_connect-1.6.1/lib/qt_connect/qt_jbindings.rb:720
            (root) at /C:/Program Files (x86)/XLibriz/lib/java/XLibriz.jar!/lib/ruby/qt_connect-1.6.1/lib/qt_connect/qt_jbindings.rb:169
           require at org/jruby/RubyKernel.java:1040
            (root) at /C:/Program Files (x86)/XLibriz/lib/java/XLibriz.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:1
           require at /C:/Program Files (x86)/XLibriz/lib/java/XLibriz.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:54
           require at file:/C:/Program Files (x86)/XLibriz/lib/java/XLibriz.jar!/app/jruby_bootstrap.rb:201
           require at org/jruby/RubyKernel.java:1040
            (root) at /C:/Program Files (x86)/XLibriz/lib/java/XLibriz.jar!/lib/ruby/qt_connect-1.6.1/lib/qt_connect.rb:6
            (root) at /C:/Program Files (x86)/XLibriz/lib/java/XLibriz.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:1
           require at /C:/Program Files (x86)/XLibriz/lib/java/XLibriz.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:54
           require at org/jruby/RubyKernel.java:1040
           require at file:/C:/Program Files (x86)/XLibriz/lib/java/XLibriz.jar!/app/jruby_bootstrap.rb:201
            (root) at /C:/Program Files (x86)/XLibriz/lib/java/XLibriz.jar!/lib/ruby/qt_connect-1.6.1/lib/Qt.rb:2
            (root) at /C:/Program Files (x86)/XLibriz/lib/java/XLibriz.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:1
           require at org/jruby/RubyKernel.java:1040
           require at /C:/Program Files (x86)/XLibriz/lib/java/XLibriz.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:54
           require at file:/C:/Program Files (x86)/XLibriz/lib/java/XLibriz.jar!/app/jruby_bootstrap.rb:201
            (root) at /C:/Program Files (x86)/XLibriz/lib/java/XLibriz.jar!/app/xlsplashup.rb:4
           require at org/jruby/RubyKernel.java:1040
            (root) at /C:/Program Files (x86)/XLibriz/lib/java/XLibriz.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:1
            (root) at -e:1

(stack, running from the filesystem using jruby-1.7.21.exe)
NoMethodError: undefined method `getMethods' for #<Class:0xc2e211>
  setup_qt_signals at C:/Projects/XLibriz/lib/ruby/qt_connect-1.6.1/lib/qt_connect/qt_jbindings.rb:341
     const_missing at C:/Projects/XLibriz/lib/ruby/qt_connect-1.6.1/lib/qt_connect/qt_jbindings.rb:323
                Qt at C:/Projects/XLibriz/lib/ruby/qt_connect-1.6.1/lib/qt_connect/qt_jbindings.rb:720
            (root) at C:/Projects/XLibriz/lib/ruby/qt_connect-1.6.1/lib/qt_connect/qt_jbindings.rb:169
           require at org/jruby/RubyKernel.java:1040
            (root) at C:/Packages/jruby-1.7.21/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:1
           require at C:/Packages/jruby-1.7.21/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:54
           require at app\jruby_bootstrap.rb:201
           require at org/jruby/RubyKernel.java:1040
            (root) at C:/Projects/XLibriz/lib/ruby/qt_connect-1.6.1/lib/qt_connect.rb:6
            (root) at C:/Packages/jruby-1.7.21/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:1
           require at C:/Packages/jruby-1.7.21/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:54
           require at org/jruby/RubyKernel.java:1040
           require at app\jruby_bootstrap.rb:201
            (root) at C:/Projects/XLibriz/lib/ruby/qt_connect-1.6.1/lib/Qt.rb:2
            (root) at C:/Packages/jruby-1.7.21/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:1
           require at org/jruby/RubyKernel.java:1040
           require at C:/Packages/jruby-1.7.21/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:54
           require at app\jruby_bootstrap.rb:201
            (root) at C:/Projects/XLibriz/app/xlsplashup.rb:4

**Comment by CeesZ** [comment]
Sorry pushed the wrong button. Did not intend to close the issu

**Comment by kares** [comment]
where did you get qt_connect **1.6.1** ... could we see its sources as the 1.5 [lines](https://github.com/CeesZ/qt_connect/blob/master/lib/qt_connect/qt_jbindings.rb#L341) do not match ?
also do you think its possible to reproduce in a way that would not need a lot of hustle? thanks

**Comment by CeesZ** [comment]
I am the author of qt_connect . I am waiting for some bugs in qtjambi 4.8.6 to be cleared and would like to get it working with jruby-9.0.0.0  before releasing the new version to GitHub. So far I did not make many changes from 1.5. What is the easiest way to get you the interim sources? It may not be trivial to isolate the bit of code from the rest, but I will give it some thought

**Comment by CeesZ** [comment]
The following short program demonstrates the problem without having to go in the complicating factors of the Qt interface:

require 'java'
javaclass = java.io.FileOutputStream
pp org.jruby.javasupport.JavaClass.getMethods(javaclass).to_a

jrb1719>jruby test3.rb
[public final native java.lang.Class java.lang.Object.getClass(),
 protected native java.lang.Object java.lang.Object.clone() throws java.lang.CloneNotSupportedException,
 public final java.io.FileDescriptor java.io.FileOutputStream.getFD() throws java.io.IOException,
 public java.nio.channels.FileChannel java.io.FileOutputStream.getChannel(),
 public boolean java.lang.Object.equals(java.lang.Object),
 public native int java.lang.Object.hashCode(),
 public final void java.lang.Object.wait(long,int) throws java.lang.InterruptedException,
 public final void java.lang.Object.wait() throws java.lang.InterruptedException,
 public final native void java.lang.Object.wait(long) throws java.lang.InterruptedException,
 public void java.io.OutputStream.close() throws java.io.IOException,
 public void java.io.OutputStream.flush() throws java.io.IOException,
 public final native void java.lang.Object.notify(),
 public void java.io.OutputStream.write(byte[],int,int) throws java.io.IOException,
 public void java.io.OutputStream.write(byte[]) throws java.io.IOException,
 public abstract void java.io.OutputStream.write(int) throws java.io.IOException,
 protected void java.lang.Object.finalize() throws java.lang.Throwable,
 public java.lang.String java.lang.Object.toString(),
 public final native void java.lang.Object.notifyAll()]

jrb1721>jruby test3.rb
NoMethodError: undefined method 'getMethods' for #<Class:0x17d9933>

**Comment by kares** [comment]
oh my bad, did not notice that method is actually gone (thought this is a Java Class conversion regression). it was really intended internal ... would you mind refactoring to no longer use it ?

you can either simply use `qtclass.java_class.getMethods` to get the "plain-java" ones or `qtclass.java_class.java_instance_methods` (and `java_class_methods` for static ones) although be advised that the later currently does not return "raw" `java.lang.Method` objects

**Comment by CeesZ** [comment]
OK, thanks. That should be a simple solution
