### ISSUE TITLE
Unexpected behavior when using `module_function` followed by `define_method`

### ISSUE THREAD

**Issue by mspoehr** [jruby/jruby#6854]
**Environment Information**

```
$ jruby -v
jruby 9.3.0.0 (2.6.8) 2021-09-17 85c20e780f OpenJDK 64-Bit Server VM 11.0.11+9 on 11.0.11+9 +jit [darwin-x86_64]
$ uname -a
Darwin HOSTNAME 20.6.0 Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:31 PDT 2021; root:xnu-7195.141.2~5/RELEASE_X86_64 x86_64
```

* No special environment variables set.
 
**Expected Behavior**

Example 1:

Using `define_method` in a module after calling `module_function` creates public module functions.

```rb
module Mod
  module_function
  define_method 'test' do
  end
end

Mod.test
```

Example 2:

Using `define_method` in a loop after calling `module_function` creates multiple public module functions.

```rb
module Mod
  module_function
  ['a', 'b'].each do |method_name|
    define_method method_name do
    end
  end
end

Mod.a
Mod.b
```

I would expect both examples to run without errors, and both do on MRI Ruby 2.5.9, 2.6.8, and JRuby 9.2.19.0. 

**Actual Behavior**

On JRuby 9.3.0.0, I get the following

Example 1:

```
NoMethodError: private method `test' called for Mod:Module
  <main> at example1.rb:7
```

Example 2:

```
NoMethodError: undefined method `a' for Mod:Module
  <main> at example2.rb:9
```

**Comment by mspoehr** [comment]
I guess `Module#test` really is a private method that already exists on any module. So I think example 2 is the real issue in either case:

```rb
module Mod
  module_function
  define_method 'a' do
  end
end

Mod.a
```

gives

```
NoMethodError: undefined method `a' for Mod:Module
  <main> at example1.rb:7
```

**Comment by enebo** [comment]
It appears to be a regression introduced in 2632240.

**Comment by enebo** [comment]
2632240 tried to reuse code but it also made at least one other mistake:

```ruby
      klass = Class.new do
        def test_method
        end
        define_method(:initialize, instance_method(:test_method))
        define_method(:initialize_copy, instance_method(:test_method))
      end
      p klass.private_methods(false)
```

We also end up marking initialize_copy as private.
