### ISSUE TITLE
Gem install errors with jruby 9.3.15.0

### ISSUE THREAD

**Issue by donoghuc** [jruby/jruby#8315]
When upgrading from jruby 9.3.14.0 to 9.3.15.0 installing gems fails with generic `(NoMethodError) undefined method 'load_defaults' for Gem::Specification:Class`. 

Full error captured from repl session:
```
#error {
 :cause "(NoMethodError) undefined method `load_defaults' for Gem::Specification:Class"
 :via
 [{:type org.jruby.exceptions.NoMethodError
   :message "(NoMethodError) undefined method `load_defaults' for Gem::Specification:Class"
   :at [RUBY <main> "uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems.rb" 1338]}]
 :trace
 [[RUBY <main> "uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems.rb" 1338]
  [org.jruby.RubyKernel require "org/jruby/RubyKernel.java" 1017]
  [RUBY <main> "uri:classloader:/jruby/kernel/gem_prelude.rb" 3]
  [org.jruby.RubyKernel load "org/jruby/RubyKernel.java" 1053]
  [RUBY <main> "file:/Users/cas.donoghue/.m2/repository/org/jruby/jruby-core/9.3.15.0/jruby-core-9.3.15.0.jar!/jruby/preludes.rb" 4]]}
```

The error happens in the `.run` here:
https://github.com/puppetlabs/jruby-utils/blob/116e6919fbedccb030e22fcf383b053ca7ba0c10/src/clj/puppetlabs/services/jruby_pool_manager/jruby_core.clj#L290-L296

We construct a `Main` object https://github.com/puppetlabs/jruby-utils/blob/116e6919fbedccb030e22fcf383b053ca7ba0c10/src/clj/puppetlabs/services/jruby_pool_manager/impl/jruby_internal.clj#L381 , here is some example config data:
```
{:gem-path
 "./target/jruby-gems:/opt/puppetlabs/server/data/puppetserver/vendored-jruby-gems",
 :splay-instance-flush true,
 :compile-mode :jit,
 :max-active-instances 1,
 :environment-vars {},
 :profiler-output-file
 "/Users/cas.donoghue/puppetlabs/jar-jar/jruby-profiler1721084411036-924981598",
 :lifecycle
 {:shutdown-on-error
  #object[puppetlabs.services.jruby.jruby_puppet_core$eval31146$initialize_and_create_jruby_config__31155$fn__31156$fn__31157 0x5f5ff26 "puppetlabs.services.jruby.jruby_puppet_core$eval31146$initialize_and_create_jruby_config__31155$fn__31156$fn__31157@5f5ff26"],
  :initialize-pool-instance
  #object[puppetlabs.services.jruby.jruby_puppet_core$eval30887$get_initialize_pool_instance_fn__30892$fn__30893$fn__30894 0x7dd6733b "puppetlabs.services.jruby.jruby_puppet_core$eval30887$get_initialize_pool_instance_fn__30892$fn__30893$fn__30894@7dd6733b"],
  :cleanup
  #object[puppetlabs.services.jruby.jruby_puppet_core$eval30915$cleanup_fn__30920 0x5a7a07df "puppetlabs.services.jruby.jruby_puppet_core$eval30915$cleanup_fn__30920@5a7a07df"],
  :initialize-scripting-container
  #object[puppetlabs.services.jruby_pool_manager.jruby_core$eval30221$default_initialize_scripting_container__30226 0x79729292 "puppetlabs.services.jruby_pool_manager.jruby_core$eval30221$default_initialize_scripting_container__30226@79729292"]},
 :max-borrows-per-instance 0,
 :multithreaded false,
 :gem-home "./target/jruby-gems",
 :ruby-load-path ("uri:classloader:/puppetserver-lib" "./target/ruby"),
 :borrow-timeout 1200000,
 :profiling-mode :off,
 :flush-timeout 1200000}
```
We the full argument list for the `.run` method on the `Main` instance is for example:
```
["-rjar-dependencies", "-e",
 "load 'jar:file:/Users/cas.donoghue/.m2/repository/org/jruby/jruby-stdlib/9.3.15.0/jruby-stdlib-9.3.15.0.jar!/META-INF/jruby.home/bin/gem'",
 "--", "install", "--no-document", "deep_merge:1.2.2"]
```

It seems like a very small diff between https://github.com/jruby/jruby/compare/9.3.14.0...9.3.15.0 versions, is there a change in `RubyInstanceConfig` we are missing with the new option?

**Comment by headius** [comment]
Hello there! This is definitely a peculiar thing to fail especially given how little changed between these two releases.

I am guessing I know the answer to this, but... was there **anything** else that might have changed on your end?

Most of the changes in 9.3.15.0 should not affect any code (IR print output filtering) and the main bug fix just made some thread-unsafe code a bit safer.

**Comment by headius** [comment]
Some things to look into:

Is it possible a different JRuby jar is getting pulled in from somewhere?

I see the `load_defaults` call in [lib/ruby/stdlib/rubygems.rb](https://github.com/rubygems/rubygems/blame/master/lib/rubygems.rb#L1400) and it's defined where it should be in [lib/ruby/stdlib/rubygems/specification.rb](https://github.com/rubygems/rubygems/blame/master/lib/rubygems/specification.rb#L849). The definition is twelve years old, and the call was moved around a bit but came in at the same commit: https://github.com/rubygems/rubygems/commit/66b70bbd77b6b9127cec0cfc4ffbb41d377def2c.

We may need to dig deeper to figure out why this is happening.

**Comment by donoghuc** [comment]
Thanks for taking a look. Yeah, I was having trouble isolating the issue as the gem loading code where its erroring occurs in the stable code you have linked. I'll go through on my end and re-check any other updates we may have slipped in. I will close this if I find anything.
