### ISSUE TITLE
Refinements not following inheritance

### ISSUE THREAD

**Issue by HoneyryderChuck** [jruby/jruby#5541]
### Environment

Provide at least:
* JRuby version (`jruby -v`) : `jruby 9.2.5.0 (2.5.0) 2018-12-06 6d5a228 OpenJDK 64-Bit Server VM 25.181-b13 on 1.8.0_181-b13 +jit [linux-x86_64]`
* Operating system and platform (e.g. `uname -a`): `Linux 4d5914318003 4.9.125-linuxkit #1 SMP Fri Sep 7 08:20:28 UTC 2018 x86_64 Linux`

### Expected Behavior

I'm refining the `URI::Generic` class, the base class of all URI's:

```ruby
module URIExtensions
   refine URI::Generic do
     def authority
        port_string = port == default_port ? nil : ":#{port}"
        "#{host}#{port_string}"
     end
   end
end
```

where I'll hopefully call this method in `URI::HTTP` and `URI::HTTPS`:

```ruby
URI("http://bang.com:8080").authority #=> "bang.com:8080"
```

this works on CRuby 2.1 -> 2.5 (probably also 2.6, didn't run it yet)

### Actual Behavior

This doesn't work:

```ruby
URI("http://bang.com:8080").authority #=> NoMethodError: undefined method `authority' for #<URI::HTTP http://bang.com>

# however, this works:

```ruby
URI::Generic.new(scheme: "http", host: "bang.com", port: "8080").authority #=> "bang.com:8080"
```

**Comment by palkan** [comment]
Looks like a duplicate of https://github.com/jruby/jruby/issues/5221

**Comment by headius** [comment]
This is *not* fixed by #5627 but should be fixed by follow-up refinement work. The issue here is likely due to problems propagating refinements from parent scopes to child scopes at scope initiation time.

**Comment by headius** [comment]
This appears to be fixed by the subsequent tweaks to super and refinements going into 9.2.7.0.

```
[] ~/projects/jruby $ cat blah.rb
module URIExtensions
  refine URI::Generic do
    def authority
      port_string = port == default_port ? nil : ":#{port}"
      "#{host}#{port_string}"
    end
  end
end

using URIExtensions

URI("http://bang.com:8080").authority
[] ~/projects/jruby $ rvm jruby-9.2.6.0 do jruby blah.rb
NoMethodError: undefined method `authority' for #<URI::HTTP http://bang.com:8080>
  <main> at blah.rb:12

[] ~/projects/jruby $ jruby -v blah.rb
jruby 9.2.7.0-SNAPSHOT (2.5.3) 2019-04-08 2122e9f OpenJDK 64-Bit Server VM 25.202-b08 on 1.8.0_202-b08 +jit [darwin-x86_64]
```

**Comment by HoneyryderChuck** [comment]
sweet ,thx!
