### ISSUE TITLE
Named Kotlin companion object throws UndefinedMethod exception

### ISSUE THREAD

**Issue by jonathanswenson** [jruby/jruby#6845]
**Environment Information**
  
Provide at least:
* JRuby version (`jruby -v`) and command line (flags, JRUBY_OPTS, etc)
`jruby 9.3.0.0-SNAPSHOT (2.6.8) 2021-09-18 ffffffffff OpenJDK 64-Bit Server VM 25.272-b10 on 1.8.0_272-b10 +jit [linux-x86_64]`

(built from source from most recent commit on master: 4727fcb3b037537ceecc67d771aa338bd5188af4 using a simple nix derivation) 
* Operating system and platform (e.g. `uname -a`)
`Linux hostname 5.10.40-1rodete2-amd64 #1 SMP Debian 5.10.40-1rodete2 (2021-06-22) x86_64 GNU/Linux`

(glinux) 

**Expected Behavior**

I’m checking out 9.3.0.0 with our application (upgrading from 9.2.16.0). 

We load in a jar that is written (mostly) in kotlin. 

There exsts some kotlin in the form: 

```kotlin
class ClassName
  ...
  companion object CompanionObjectName {
	...
  }
}
```

on 9.2.16.0, our application would reference this companion object via the syntax: 
`com.x.y.ClassName.CompanionObjectName.create(...)`

**Actual Behavior**

but after upgrading to 9.3.0.0 that threw an error: 
`NoMethodError: undefined method `CompanionObjectName' for Java::ComXY::ClassName:Module`

To get this to work I had to change to: 
`com.x.y.ClassName::CompanionObjectName.create(...)`

**Comment by jonathanswenson** [comment]
repro: (using gradle 6.8.3)

build with `./gradlew shadowJar` to get kotlin runtime. 

tree: omitted gradle wrappers
```
.
├── build.gradle.kts
├── repro.rb
├── settings.gradle.kts
└── src
    └── main
        └── kotlin
            └── com
                └── looker
                    └── foo
                        └── TestClass.kt
```

## build.gradle.kts
```
plugins {
    id("org.jetbrains.kotlin.jvm") version "1.5.0"
    id("com.github.johnrengelman.shadow") version "6.1.0"
}

repositories {
    mavenCentral()
}

dependencies {
    implementation(platform("org.jetbrains.kotlin:kotlin-bom"))
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
}
```

## settings.gradle.kts
```
rootProject.name = "jruby_repro"
```

## src/main/kotlin/com/looker/foo/TestClass.kt

package com.looker.foo

class TestClass {
  companion object TestCompanionObject {
    @JvmStatic
    fun doit() {
      println("done")
    }
  }
}

# repro.rb
```
require_relative './build/libs/jruby_repro-all.jar'

com.looker.foo.TestClass::TestCompanionObject.doit()
com.looker.foo.TestClass.NamedCompanionObject.doit()
```

**Comment by headius** [comment]
Could you turn this into an example repo? It might form the basis of a test kit for our Kotlin integration.
