### ISSUE TITLE
Regression in compiling with default 1.8 mode

### ISSUE THREAD

**Issue by BanzaiMan** [jruby/jruby#1679]
When RVM installs JRuby with a non-default language mode (e.g., 1.8), it runs `mvn` with `-Djruby.default.ruby.version=1.8`.

This worked well for JRuby 1.7.11, but this no longer works with 1.7.12 release.

The failure looks like this (I removed irrelevant output while maven downloads the Internets):

``` sh-session
mvn -Djruby.default.ruby.version=1.8
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] JRuby
[INFO] JRuby Core
[INFO] JRuby Ext
[INFO] JRuby OpenSSL
[INFO] JRuby Readline
[INFO] JRuby Ripper
[INFO] JRuby Lib Setup
[INFO]

⋮

[INFO]
[INFO] --- tesla-polyglot-maven-plugin:0.0.9:execute (install_gems) @ jruby-lib ---
NoMethodError: undefined method `match' for :clean:Symbol
    plugin_gav at file:/home/travis/.m2/repository/de/saumya/mojo/maven-tools/0.34.2/maven-tools-0.34.2.jar!/maven/tools/dsl.rb:643
        plugin at file:/home/travis/.m2/repository/de/saumya/mojo/maven-tools/0.34.2/maven-tools-0.34.2.jar!/maven/tools/dsl.rb:666
      eval_pom at (eval):39
          call at org/jruby/RubyProc.java:290
          call at org/jruby/RubyProc.java:224
  nested_block at file:/home/travis/.m2/repository/de/saumya/mojo/maven-tools/0.34.2/maven-tools-0.34.2.jar!/maven/tools/dsl.rb:1084
       project at file:/home/travis/.m2/repository/de/saumya/mojo/maven-tools/0.34.2/maven-tools-0.34.2.jar!/maven/tools/dsl.rb:347
      eval_pom at (eval):18
          call at org/jruby/RubyProc.java:290
          call at org/jruby/RubyProc.java:224
  nested_block at file:/home/travis/.m2/repository/de/saumya/mojo/maven-tools/0.34.2/maven-tools-0.34.2.jar!/maven/tools/dsl.rb:1084
         tesla at file:/home/travis/.m2/repository/de/saumya/mojo/maven-tools/0.34.2/maven-tools-0.34.2.jar!/maven/tools/dsl.rb:19
      eval_pom at (eval):1
          eval at org/jruby/RubyKernel.java:1096
      eval_pom at file:/home/travis/.m2/repository/de/saumya/mojo/maven-tools/0.34.2/maven-tools-0.34.2.jar!/maven/tools/dsl.rb:50
         parse at parser.rb:52
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] JRuby ............................................. SUCCESS [  0.674 s]
[INFO] JRuby Core ........................................ SUCCESS [ 23.993 s]
[INFO] JRuby Ext ......................................... SUCCESS [  0.004 s]
[INFO] JRuby OpenSSL ..................................... SUCCESS [  1.022 s]
[INFO] JRuby Readline .................................... SUCCESS [  0.122 s]
[INFO] JRuby Ripper ...................................... SUCCESS [  0.288 s]
[INFO] JRuby Lib Setup ................................... FAILURE [ 17.206 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 44.052 s
[INFO] Finished at: 2014-05-04T04:43:02+00:00
[INFO] Final Memory: 32M/224M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.tesla.polyglot:tesla-polyglot-maven-plugin:0.0.9:execute (install_gems) on project jruby-lib: Execution install_gems of goal io.tesla.polyglot:tesla-polyglot-maven-plugin:0.0.9:execute failed: (NoMethodError) undefined method `match' for :clean:Symbol -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :jruby-lib
```
