### ISSUE TITLE
JRuby 9.1 package possibly broken?

### ISSUE THREAD

**Issue by mlen** [jruby/jruby#4707]
### Environment

[Travis CI trusty image and rvm](https://travis-ci.org/whitequark/parser/builds/250286036), but this also happens in a clean ubuntu lts docker image, also installing via rvm. After discussing the issue with @mpapis, we came to the conclusion that there is probably something wrong with 9.1 package. 1.7 packages work fine.

### Expected Behavior

* After installing, `racc` executable should be installed, this works with 1.7

### Actual Behavior

* With 9.1, `racc` executable is not present and the build fails with code 127, which means that this command was not found

**Comment by kares** [comment]
seems that CI build is fine therse days - 1.7 passes and there's a different kind of failure with 9.1 : 
likely due expecting full TracePoint API *NoMethodError: undefined method `trace' for TracePoint:Class*
