### ISSUE TITLE
CSV::Row does not have .to_h

### ISSUE THREAD

**Issue by mjc** [jruby/jruby#2315]
jruby 1.7.17 

```
CSV.read(file_name,headers: true).first.to_h
NoMethodError: undefined method `to_h' for #<CSV::Row:0x68ab0936>
```

jruby 9k (7a66d8b)

```
CSV.read(file_name,headers: true).first.to_h
NoMethodError: undefined method `to_h' for #<CSV::Row:0xb4a2758>
```

This works on MRI 2.1.0 and possibly older versions as well - it creates a hash with the headers of the CSV as the keys.
