### ISSUE TITLE
JRuby 1.7.2 with authlogic 3.x fails to boot (OpenSSL)

### ISSUE THREAD

**Issue by youngbrioche** [jruby/jruby#541]
When upgrading from JRuby 1.6.8 to 1.7.2 my application fails to boot within Tomcat 6 on Windows. Looks like this is somehow related to the bundled jruby-openssl in JRuby 1.7.*

The resulting line 1 in `authlogic-3.2.0/lib/authlogic/crypto_providers/aes256.rb` just does a plain

``` ruby
require "openssl"
```

Tomcat log output:

```
Feb 19, 2013 11:15:36 AM org.apache.catalina.core.ApplicationContext log
INFO: INFO: added application to pool, size now = 2
Feb 19, 2013 11:17:14 AM org.apache.catalina.core.ApplicationContext log
INFO: INFO: pool was empty - getting new application instance
Feb 19, 2013 11:17:28 AM org.apache.catalina.core.ApplicationContext log
SEVERE: ERROR: application error
org.jruby.rack.RackInitializationException: load error: openssl -- java.lang.NoClassDefFoundError: org/bouncycastle/asn1/DERBoolean
    from org/jruby/RubyKernel.java:1027:in `require'
    from C:/Program Files/Apache Software Foundation/Tomcat 6.0/temp/0-umt/WEB-INF/gems/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:251:in `require'
    from C:/Program Files/Apache Software Foundation/Tomcat 6.0/temp/0-umt/WEB-INF/gems/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:236:in `load_dependency'
    from C:/Program Files/Apache Software Foundation/Tomcat 6.0/temp/0-umt/WEB-INF/gems/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:251:in `require'
    from C:/Program Files/Apache Software Foundation/Tomcat 6.0/temp/0-umt/WEB-INF/gems/gems/authlogic-3.2.0/lib/authlogic/crypto_providers/aes256.rb:1:in `(root)'
    from org/jruby/RubyKernel.java:1027:in `require'
    from C:/Program Files/Apache Software Foundation/Tomcat 6.0/temp/0-umt/WEB-INF/gems/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:1:in `(root)'
    from C:/Program Files/Apache Software Foundation/Tomcat 6.0/temp/0-umt/WEB-INF/gems/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:251:in `require'
    from C:/Program Files/Apache Software Foundation/Tomcat 6.0/temp/0-umt/WEB-INF/gems/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:236:in `load_dependency'
    from C:/Program Files/Apache Software Foundation/Tomcat 6.0/temp/0-umt/WEB-INF/gems/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:251:in `require'
    from org/jruby/RubyArray.java:1613:in `each'
    from C:/Program Files/Apache Software Foundation/Tomcat 6.0/temp/0-umt/WEB-INF/gems/gems/authlogic-3.2.0/lib/authlogic.rb:60:in `(root)'
    from org/jruby/RubyKernel.java:1027:in `require'
    from C:/Program Files/Apache Software Foundation/Tomcat 6.0/temp/0-umt/WEB-INF/gems/gems/authlogic-3.2.0/lib/authlogic.rb:5:in `(root)'
    from C:/Program Files/Apache Software Foundation/Tomcat 6.0/temp/0-umt/WEB-INF/gems/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:1:in `(root)'
    from C:/Program Files/Apache Software Foundation/Tomcat 6.0/temp/0-umt/WEB-INF/gems/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:251:in `require'
    from C:/Program Files/Apache Software Foundation/Tomcat 6.0/temp/0-umt/WEB-INF/gems/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:236:in `load_dependency'
    from org/jruby/RubyKernel.java:1027:in `require'
    from C:/Program Files/Apache Software Foundation/Tomcat 6.0/temp/0-umt/WEB-INF/gems/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:251:in `require'
    from C:/Program Files/Apache Software Foundation/Tomcat 6.0/temp/0-umt/WEB-INF/gems/gems/iqvoc-4.0.7/lib/../config/engine.rb:6:in `(root)'
    from org/jruby/RubyKernel.java:1027:in `require'
    from C:/Program Files/Apache Software Foundation/Tomcat 6.0/temp/0-umt/WEB-INF/gems/gems/iqvoc-4.0.7/lib/iqvoc.rb:1:in `(root)'
    from org/jruby/RubyArray.java:1613:in `each'
    from C:/Program Files/Apache Software Foundation/Tomcat 6.0/temp/0-umt/WEB-INF/gems/gems/iqvoc-4.0.7/lib/iqvoc.rb:27:in `Iqvoc'
    from org/jruby/RubyArray.java:1613:in `each'
    from C:/Program Files/Apache Software Foundation/Tomcat 6.0/temp/0-umt/WEB-INF/gems/gems/iqvoc-4.0.7/lib/iqvoc.rb:25:in `(root)'
    from C:/Program Files/Apache Software Foundation/Tomcat 6.0/temp/0-umt/WEB-INF/gems/gems/bundler-1.2.3/lib/bundler/runtime.rb:1:in `(root)'
    from C:/Program Files/Apache Software Foundation/Tomcat 6.0/temp/0-umt/WEB-INF/gems/gems/bundler-1.2.3/lib/bundler/runtime.rb:68:in `require'
    from org/jruby/RubyKernel.java:1027:in `require'
    from C:/Program Files/Apache Software Foundation/Tomcat 6.0/temp/0-umt/WEB-INF/gems/gems/bundler-1.2.3/lib/bundler/runtime.rb:66:in `require'
    from org/jruby/RubyKernel.java:1027:in `require'
    from C:/Program Files/Apache Software Foundation/Tomcat 6.0/temp/0-umt/WEB-INF/gems/gems/bundler-1.2.3/lib/bundler/runtime.rb:55:in `require'
    from C:/Program Files/Apache Software Foundation/Tomcat 6.0/temp/0-umt/WEB-INF/gems/gems/bundler-1.2.3/lib/bundler.rb:128:in `require'
    from C:/Program Files/Apache Software Foundation/Tomcat 6.0/temp/0-umt/WEB-INF/config/application.rb:12:in `(root)'

    at org.jruby.rack.DefaultRackApplicationFactory$4.init(DefaultRackApplicationFactory.java:231)
    at org.jruby.rack.DefaultRackApplicationFactory.getApplication(DefaultRackApplicationFactory.java:58)
    at org.jruby.rack.PoolingRackApplicationFactory.createApplication(PoolingRackApplicationFactory.java:323)
    at org.jruby.rack.PoolingRackApplicationFactory.getApplication(PoolingRackApplicationFactory.java:171)
    at org.jruby.rack.DefaultRackDispatcher.getApplication(DefaultRackDispatcher.java:27)
    at org.jruby.rack.AbstractRackDispatcher.process(AbstractRackDispatcher.java:32)
    at org.jruby.rack.AbstractFilter.doFilter(AbstractFilter.java:66)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:128)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:293)
    at org.apache.jk.server.JkCoyoteHandler.invoke(JkCoyoteHandler.java:190)
    at org.apache.jk.common.HandlerRequest.invoke(HandlerRequest.java:291)
    at org.apache.jk.common.ChannelSocket.invoke(ChannelSocket.java:769)
    at org.apache.jk.common.ChannelSocket.processConnection(ChannelSocket.java:698)
    at org.apache.jk.common.ChannelSocket$SocketConnection.runIt(ChannelSocket.java:891)
    at org.apache.tomcat.util.threads.ThreadPool$ControlRunnable.run(ThreadPool.java:690)
    at java.lang.Thread.run(Thread.java:662)
```
