### ISSUE TITLE
Script Engine Managers fail to load in JDK9+

### ISSUE THREAD

**Issue by jonathanswenson** [jruby/jruby#5446]
### Summary

Instantiation of a javax.script.ScriptEngineManager from a jruby program throws a `java.lang.NoClassDefFoundError javax/script/ScriptEngineFactory` exception using JDK 9+. 

### Environment

```
jruby -version
jruby 9.1.17.0 (2.3.3) 2018-04-20 d8b1ff9 OpenJDK 64-Bit Server VM 9.0.4+11 on 9.0.4+11 +jit [darwin-x86_64]

java -version
openjdk version "9.0.4"
OpenJDK Runtime Environment (build 9.0.4+11)
OpenJDK 64-Bit Server VM (build 9.0.4+11, mixed mode)

uname -a
Darwin <hostname> 17.7.0 Darwin Kernel Version 17.7.0: Fri Jul  6 19:54:51 PDT 2018; root:xnu-4570.71.3~2/RELEASE_X86_64 x86_64
```

This is reproducible on Oracle JDK 9 and 11 and OpenJDK 9, 10, 11. Did not try with OracleJDK 10. 
Using JRuby 9.2.3.0 (tried with open jdk 9) does not solve the problem. 

### Expected Behavior

We use a script engine to execute non-ruby code via JRuby. Using Java 8, we are able to instantiate an instance of the ScriptEngineManager via the following code: 
```
puts "java_vm: #{java.lang.System.getProperty('java.vm.name')}"
puts "java_version: #{java.lang.System.getProperty('java.version')}"
puts "ruby_version: #{JRUBY_VERSION}"

script_engine_manager = javax.script.ScriptEngineManager.new()
puts script_engine_manager
```

The expected behavior of running this results in the following under openJDK 8:
```
$ jruby test_script_engine_manager.rb
java_vm: OpenJDK 64-Bit Server VM
java_version: 1.8.0_192
ruby_version: 9.1.17.0
javax.script.ScriptEngineManager@491cc5c9
```

### Actual Behavior

When running under open jdk 9:
```
java_vm: OpenJDK 64-Bit Server VM
java_version: 9.0.4
ruby_version: 9.1.17.0
Unhandled Java exception: java.lang.NoClassDefFoundError: javax/script/ScriptEngineFactory
java.lang.NoClassDefFoundError: javax/script/ScriptEngineFactory
        findBootstrapClass at java/lang/ClassLoader.java:-2
  findBootstrapClassOrNull at java/lang/ClassLoader.java:1248
  findBootstrapClassOrNull at java/lang/System.java:2123
           loadClassOrNull at jdk/internal/loader/ClassLoaders.java:125
           loadClassOrNull at jdk/internal/loader/BuiltinClassLoader.java:617
           loadClassOrNull at jdk/internal/loader/BuiltinClassLoader.java:641
           loadClassOrNull at jdk/internal/loader/BuiltinClassLoader.java:617
                 loadClass at jdk/internal/loader/BuiltinClassLoader.java:580
                 loadClass at jdk/internal/loader/ClassLoaders.java:185
                 loadClass at java/lang/ClassLoader.java:550
                 loadClass at java/lang/ClassLoader.java:496
                  forName0 at java/lang/Class.java:-2
                   forName at java/lang/Class.java:375
         nextProviderClass at java/util/ServiceLoader.java:1204
            hasNextService at java/util/ServiceLoader.java:1215
                   hasNext at java/util/ServiceLoader.java:1259
                   hasNext at java/util/ServiceLoader.java:1294
                   hasNext at java/util/ServiceLoader.java:1379
               initEngines at javax/script/ScriptEngineManager.java:120
                      init at javax/script/ScriptEngineManager.java:84
                    <init> at javax/script/ScriptEngineManager.java:62
              newInstance0 at jdk/internal/reflect/NativeConstructorAccessorImpl.java:-2
               newInstance at jdk/internal/reflect/NativeConstructorAccessorImpl.java:62
               newInstance at jdk/internal/reflect/DelegatingConstructorAccessorImpl.java:45
               newInstance at java/lang/reflect/Constructor.java:488
         newInstanceDirect at org/jruby/javasupport/JavaConstructor.java:262
               newInstance at org/jruby/RubyClass.java:995
                      call at org/jruby/RubyClass$INVOKER$i$newInstance.gen:-1
         invokeOther20:new at test_script_engine_manager.rb:13
                    <main> at test_script_engine_manager.rb:13
       invokeWithArguments at java/lang/invoke/MethodHandle.java:638
                 runScript at org/jruby/Ruby.java:830
               runNormally at org/jruby/Ruby.java:749
               runNormally at org/jruby/Ruby.java:767
               runFromMain at org/jruby/Ruby.java:580
             doRunFromMain at org/jruby/Main.java:417
               internalRun at org/jruby/Main.java:305
                       run at org/jruby/Main.java:232
                      main at org/jruby/Main.java:204
```

The full Java exception is: 
```
java.lang.NoClassDefFoundError: javax/script/ScriptEngineFactory
	at java.lang.ClassLoader.findBootstrapClass(Native Method)
	at java.lang.ClassLoader.findBootstrapClassOrNull(java/lang/ClassLoader.java:1257)
	at java.lang.System$2.findBootstrapClassOrNull(java/lang/System.java:2126)
	at jdk.internal.loader.ClassLoaders$BootClassLoader.loadClassOrNull(jdk/internal/loader/ClassLoaders.java:118)
	at jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(jdk/internal/loader/BuiltinClassLoader.java:618)
	at jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(jdk/internal/loader/BuiltinClassLoader.java:642)
	at jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(jdk/internal/loader/BuiltinClassLoader.java:618)
	at jdk.internal.loader.BuiltinClassLoader.loadClass(jdk/internal/loader/BuiltinClassLoader.java:581)
	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(jdk/internal/loader/ClassLoaders.java:178)
	at java.lang.ClassLoader.loadClass(java/lang/ClassLoader.java:575)
	at java.lang.ClassLoader.loadClass(java/lang/ClassLoader.java:521)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(java/lang/Class.java:398)
	at java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(java/util/ServiceLoader.java:1209)
	at java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(java/util/ServiceLoader.java:1220)
	at java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(java/util/ServiceLoader.java:1264)
	at java.util.ServiceLoader$2.hasNext(java/util/ServiceLoader.java:1299)
	at java.util.ServiceLoader$3.hasNext(java/util/ServiceLoader.java:1384)
	at javax.script.ScriptEngineManager.initEngines(javax/script/ScriptEngineManager.java:123)
	at javax.script.ScriptEngineManager.init(javax/script/ScriptEngineManager.java:87)
	at javax.script.ScriptEngineManager.<init>(javax/script/ScriptEngineManager.java:62)
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(jdk/internal/reflect/NativeConstructorAccessorImpl.java:62)
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(jdk/internal/reflect/DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(java/lang/reflect/Constructor.java:490)
	at org.jruby.javasupport.JavaConstructor.newInstanceDirect(org/jruby/javasupport/JavaConstructor.java:262)
	at org.jruby.RubyClass.newInstance(org/jruby/RubyClass.java:995)
	at org.jruby.RubyClass$INVOKER$i$newInstance.call(org/jruby/RubyClass$INVOKER$i$newInstance.gen)
	at test_script_engine_manager.invokeOther20:new(test_scripting_engine_manager.rb:23)
	at test_script_engine_manager.<main>(test_script_engine_manager.rb:23)
	at java.lang.invoke.MethodHandle.invokeWithArguments(java/lang/invoke/MethodHandle.java:710)
	at org.jruby.Ruby.runScript(org/jruby/Ruby.java:830)
	at org.jruby.Ruby.runNormally(org/jruby/Ruby.java:749)
	at org.jruby.Ruby.runNormally(org/jruby/Ruby.java:767)
	at org.jruby.Ruby.runFromMain(org/jruby/Ruby.java:580)
	at org.jruby.Main.doRunFromMain(org/jruby/Main.java:417)
	at org.jruby.Main.internalRun(org/jruby/Main.java:305)
	at org.jruby.Main.run(org/jruby/Main.java:232)
	at org.jruby.Main.main(org/jruby/Main.java:204)
```

**Comment by headius** [comment]
Hmm I cannot reproduce here:

```
[] ~/projects/jruby $ jruby blah.rb
java_vm: Java HotSpot(TM) 64-Bit Server VM
java_version: 1.8.0_181
ruby_version: 9.2.5.0-SNAPSHOT
javax.script.ScriptEngineManager@33c7e1bb

[] ~/projects/jruby $ pickjdk 3
New JDK: jdk-11.jdk

[] ~/projects/jruby $ jruby blah.rb
java_vm: Java HotSpot(TM) 64-Bit Server VM
java_version: 11
ruby_version: 9.2.5.0-SNAPSHOT
javax.script.ScriptEngineManager@23ea8830

[] ~/projects/jruby $ pickjdk 4
New JDK: jdk-9.0.4.jdk

[] ~/projects/jruby $ jruby blah.rb
java_vm: Java HotSpot(TM) 64-Bit Server VM
java_version: 9.0.4
ruby_version: 9.2.5.0-SNAPSHOT
javax.script.ScriptEngineManager@647fb583
```

Is it possible your installation of 9 is missing javax.script somehow? Are you running with more restrictive module settings or something?

**Comment by headius** [comment]
Oh I just realized you were using 9.1.17.0. I can indeed reproduce your issue with that version of JRuby:

```
[] ~/projects/jruby $ rvm jruby-9.1.17.0 do jruby blah.rb
java_vm: Java HotSpot(TM) 64-Bit Server VM
java_version: 9.0.4
ruby_version: 9.1.17.0
Unhandled Java exception: java.lang.NoClassDefFoundError: javax/script/ScriptEngineFactory
java.lang.NoClassDefFoundError: javax/script/ScriptEngineFactory
```

JRuby 9.1.x did not have good support for Java 9+, but JRuby 9.2.x should work well on 9, 10, and 11.

JRuby 9.2.1 in particular modified the JRuby startup script (written in bash) to specify module flags that appear to fix this problem. However those flags have not yet made it into the native launcher (the jruby-launcher gem, installed automatically by some Ruby managers) so depending on how you install JRuby you may still see this:

```
$ jruby -v blah.rb
jruby 9.2.4.0 (2.5.0) 2018-11-13 8faff06 Java HotSpot(TM) 64-Bit Server VM 11+28 on 11+28 +jit [darwin-x86_64]
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.jruby.util.SecurityHelper to field java.lang.reflect.Field.modifiers
WARNING: Please consider reporting this to the maintainers of org.jruby.util.SecurityHelper
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
java_vm: Java HotSpot(TM) 64-Bit Server VM
java_version: 11
ruby_version: 9.2.4.0
Unhandled Java exception: java.lang.NoClassDefFoundError: javax/script/ScriptEngineFactory
```

The native launcher has a flag that appears to help: `-Xnobootclasspath` which disables use of the JVM's "boot classpath" that's now forbidden under Java 9+ modules.

```
$ jruby -v -Xnobootclasspath blah.rb
jruby 9.2.4.0 (2.5.0) 2018-11-13 8faff06 Java HotSpot(TM) 64-Bit Server VM 11+28 on 11+28 +jit [darwin-x86_64]
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.jruby.util.SecurityHelper (file:/Users/headius/.rvm/rubies/jruby-9.2.4.0/lib/jruby.jar) to field java.lang.reflect.Field.modifiers
WARNING: Please consider reporting this to the maintainers of org.jruby.util.SecurityHelper
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
java_vm: Java HotSpot(TM) 64-Bit Server VM
java_version: 11
ruby_version: 9.2.4.0
javax.script.ScriptEngineManager@7eaa2bc6
```

This also appears to work with 9.1.17.0:

```
$ jruby -v -Xnobootclasspath blah.rb
jruby 9.1.17.0 (2.3.3) 2018-04-20 d8b1ff9 Java HotSpot(TM) 64-Bit Server VM 11+28 on 11+28 +jit [darwin-x86_64]
java_vm: Java HotSpot(TM) 64-Bit Server VM
java_version: 11
ruby_version: 9.1.17.0
javax.script.ScriptEngineManager@60c96eb4
```

**Comment by headius** [comment]
I've pushed jruby-launcher 1.1.7. Can you try installing it and see if it helps your issue?

**Comment by jonathanswenson** [comment]
@headius using `-Xnobootclasspath` does solve the issue for me. 

After installing JRuby launcher the problem appears to go away without requiring the `-Xnobootclasspath` option

with jruby-launcher 1.1.7 installed the executable is run with: `--module-path path/to/lib/jruby.jar:`
as opposed to the `-cp "" -Xbootclasspath/a:path/to/lib/jruby.jar` option that was run with 1.1.6 installed

**Comment by apple-corps** [comment]
I'm seeing a similar message but it states my jvm doesn't support scripting. Is there a clear way to know which JVM I should try to use where the Script Engine Manager should load?

Using system java: /usr/bin/java
jruby 9.2.16.0 (2.5.7) 2021-03-03 f82228dc32 OpenJDK 64-Bit Server VM 11.0.11+9-LTS on 11.0.11+9-LTS +indy [linux-x86_64]

Stack trace here:

https://github.com/logstash-plugins/logstash-filter-aggregate/issues/119#issuecomment-981384890

**Comment by apple-corps** [comment]
@headius @jonathanswenson ^^

**Comment by apple-corps** [comment]
I'm invoking via https://github.com/elastic/logstash/blob/main/bin/rspec so not sure if I should try setting `-Xnobootclasspath` by export JRUBY_OPTS="-Xnobootclasspath" but maybe not relevant if log says my JVM doesn't support scripting.

**Comment by headius** [comment]
@apple-corps I have never seen this error before! That is pretty weird. The scripting APIs are a standard part of JDK, albeit not part of the `java.base` profile that normally loads.

My guess is that you are using a "JRE" that has been repackaged to remove most of the optional/extended JDK packages. This would make it a packaging issue.

Could you open a new issue about this? I don't think there's anything we can do about it, but I would like to discuss this and see if we can figure out what's so weird about your OpenJDK install.

**Comment by apple-corps** [comment]
@headius Thanks! : https://github.com/jruby/jruby/issues/6950 . Let me know if you have another JVM to suggest. I'd like to try to resolve this to see if it fixes my issue executing the test on the linked issue.
