### ISSUE TITLE
Jruby debugger not working

### ISSUE THREAD

**Issue by amiracam** [jruby/jruby#6018]
Comments:

I believe this a known issue , however I can't find a ticket for it i.e. at least easily

Environment
Intellij IDEA JRuby plug
  
Provide at least:
* JRuby version (`jruby -v`) and command line (flags, JRUBY_OPTS, etc)

jruby 9.2.9.0 (2.5.7) 2019-10-30 458ad3e OpenJDK 64-Bit Server VM 25.212-b04 on 1.8.0_212-b04 +jit [mswin32-x86_64]

* Operating system and platform (e.g. `uname -a`)
Windows / MAC
Other relevant info you may wish to add:

**Expected Behavior**
for starters I expected to be able to start the debugger , not able to do so 

* Describe your expectation of how JRuby should behave, perhaps by showing how CRuby/MRI behaves.

I expect the debugger to start and stop within a breakpoint, walk thru code, etc

* Provide an executable Ruby script or a link to an example repository.

testDebugger.rb >>>
a = 5  # set breakpoint
b = 10
c = a + b
puts "Sum of a + b is: #{c}"
<<<

**Actual Behavior**
starting a debug session in IDEA immediately crashes with the following stack:

> C:\jruby-9.2.9.0\bin\jruby.exe -J-cp C:\Users\Charles\IdeaProjects\TestDebugger\out\production\TestDebugger -X+O -J-Djruby.compile.mode=OFF -J-Djruby.debug.fullTrace=true C:\jruby-9.2.9.0\lib\ruby\gems\shared\gems\ruby-debug-ide-0.7.0\bin\rdebug-ide --key-value --disable-int-handler --evaluation-timeout 10 --evaluation-control --time-limit 100 --memory-limit 0 --rubymine-protocol-extensions --port 55655 --host 0.0.0.0 --dispatcher-port 55656 -- C:/Users/Charles/IdeaProjects/TestDebugger/src/testDebugger.rb
Evaluation memory limit is ineffective in JRuby and MRI < 2.0
Unhandled Java exception: java.lang.IllegalArgumentException: unknown event type: c_call
java.lang.IllegalArgumentException: unknown event type: c_call
      typeForEvent at org/jruby/debug/Util.java:131
      eventHandler at org/jruby/debug/DebugEventHook.java:97
             event at org/jruby/runtime/EventHook.java:32
    callEventHooks at org/jruby/Ruby.java:3195
             trace at org/jruby/runtime/ThreadContext.java:745
             trace at org/jruby/runtime/ThreadContext.java:741
         callTrace at org/jruby/internal/runtime/methods/JavaMethod.java:189
              call at org/jruby/RubyHash$INVOKER$i$1$0$op_aref_DBG.gen:-1
      cacheAndCall at org/jruby/runtime/callsite/CachingCallSite.java:375
              call at org/jruby/runtime/callsite/CachingCallSite.java:174
       processCall at org/jruby/ir/interpreter/InterpreterEngine.java:316
         interpret at org/jruby/ir/interpreter/StartupInterpreterEngine.java:72
         interpret at org/jruby/ir/interpreter/InterpreterEngine.java:80
  INTERPRET_METHOD at org/jruby/internal/runtime/methods/InterpretedIRMethod.java:123
              call at org/jruby/internal/runtime/methods/InterpretedIRMethod.java:110
      cacheAndCall at org/jruby/runtime/callsite/CachingCallSite.java:354
              call at org/jruby/runtime/callsite/CachingCallSite.java:143
       processCall at org/jruby/ir/interpreter/InterpreterEngine.java:345
         interpret at org/jruby/ir/interpreter/StartupInterpreterEngine.java:72
  INTERPRET_METHOD at org/jruby/internal/runtime/methods/InterpretedIRMethod.java:87
              call at org/jruby/internal/runtime/methods/InterpretedIRMethod.java:66
      cacheAndCall at org/jruby/runtime/callsite/CachingCallSite.java:332
              call at org/jruby/runtime/callsite/CachingCallSite.java:86
         interpret at org/jruby/ir/instructions/CallBase.java:540
       processCall at org/jruby/ir/interpreter/InterpreterEngine.java:361
         interpret at org/jruby/ir/interpreter/StartupInterpreterEngine.java:72
         interpret at org/jruby/ir/interpreter/InterpreterEngine.java:86
  INTERPRET_METHOD at org/jruby/internal/runtime/methods/InterpretedIRMethod.java:159
              call at org/jruby/internal/runtime/methods/InterpretedIRMethod.java:146
      cacheAndCall at org/jruby/runtime/callsite/CachingCallSite.java:375
              call at org/jruby/runtime/callsite/CachingCallSite.java:174
       processCall at org/jruby/ir/interpreter/InterpreterEngine.java:316
         interpret at org/jruby/ir/interpreter/StartupInterpreterEngine.java:72
         interpret at org/jruby/ir/interpreter/InterpreterEngine.java:86
  INTERPRET_METHOD at org/jruby/internal/runtime/methods/InterpretedIRMethod.java:159
              call at org/jruby/internal/runtime/methods/InterpretedIRMethod.java:146
      cacheAndCall at org/jruby/runtime/callsite/CachingCallSite.java:375
              call at org/jruby/runtime/callsite/CachingCallSite.java:174
       processCall at org/jruby/ir/interpreter/InterpreterEngine.java:316
         interpret at org/jruby/ir/interpreter/StartupInterpreterEngine.java:72
    INTERPRET_ROOT at org/jruby/ir/interpreter/Interpreter.java:96
           execute at org/jruby/ir/interpreter/Interpreter.java:81
           execute at org/jruby/ir/interpreter/Interpreter.java:30
           execute at org/jruby/ir/IRTranslator.java:42
    runInterpreter at org/jruby/Ruby.java:892
    runInterpreter at org/jruby/Ruby.java:896
       runNormally at org/jruby/Ruby.java:785
       runNormally at org/jruby/Ruby.java:798
       runFromMain at org/jruby/Ruby.java:610
     doRunFromMain at org/jruby/Main.java:412
       internalRun at org/jruby/Main.java:304
               run at org/jruby/Main.java:234
              main at org/jruby/Main.java:206

Process finished with exit code 1

* Describe or show the actual behavior.
* Provide text or screen capture showing the behavior.

**If You Need Help**

* Join us on Matrix at https://matrix.to/#/#jruby:matrix.org

**Comment by enebo** [comment]
This was fixed by https://github.com/ruby-debug/ruby-debug/pull/30 but I don't know how you update this gem within idea or how that all works?

**Comment by amiracam** [comment]
Gem file for now

**Comment by headius** [comment]
Duplicate of #5954.

**Comment by Confusion** [comment]
I can't get the debugger to work on JRuby 9.2.9.0. 

Up until JRuby 9.2.8.0 I just listed 'ruby-debug' in the Gemfile, did a `require 'ruby-debug'` in e.g. my `spec_helper.rb` and could then use `debugger` in a spec. This was with both `ruby-debug` and `ruby-debug-base` 0.10.6. As reported those don't work for JRuby 9.2.9.0 (in my case stumbling over a `unknown event type: b_call`). 

Now there's a `ruby-debug-base` 0.11.0 on rubygems.org, but no `ruby-debug` 0.11.0. I can't upgrade just `ruby-debug-base`. If I switch to listing 'ruby-debug-base' in the Gemfile and just require that, the debugger fails with `undefined method `run_init_script' for Debugger:Module`. I don't understand what I should do to make it work. Should there actually also be a `ruby-debug` 0.11.0 and is that the problem?

**Comment by headius** [comment]
@Confusion Sorry we did not see your update here. Can you perhaps push a small example project that shows the problem? I must admit I'm not sure of the relation between `ruby-debug` and `ruby-debug-base` gems, but you may be right that a new release of `ruby-debug` is necessary to pick up the appropriate dependencies.

**Comment by amiracam** [comment]
@Confusion and you shouldn't have to even do that i.e. at least thru Intellij Idea / Rubymine , it just worked i.e. in the 9.1.x series , I fell off Jruby for a bit , but came back to it lately and managed to figure how to integrate it with Gradle which I need for full adoption, but now the debugger is broken

**Comment by Confusion** [comment]
@headius You can reproduce it using the following (assuming bundler is installed):
```
require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'
  gem 'ruby-debug'
  # gem 'ruby-debug-base', '= 0.11.0'    
end

require 'ruby-debug'

debugger
```

Running `jruby --dev --debug script.rb` with jruby-9.2.9.0 results in ruby-debug 0.10.6 and dependencies being installed by bundler, followed by `Unhandled Java exception: java.lang.IllegalArgumentException: unknown event type: b_call`.

With jruby-9.2.8.0 the script works and you will enter the debugger.

Uncommenting the `gem 'ruby-debug-base', '= 0.11.0'` causes bundler to resolve
'ruby-debug' to 0.7.5 (non-java), which results in a `Gem::Ext::BuildError` as it attempts to compile the native extension.

Attempting to force 'ruby-debug' to 0.10.6, using `gem 'ruby-debug', '= 0.10.6'` in the gemfile block, results in 
```
Bundler could not find compatible versions for gem "ruby-debug-base":
  In Gemfile:
    ruby-debug-base (= 0.11.0) java

    ruby-debug (= 0.10.6) java was resolved to 0.10.6, which depends on
      ruby-debug-base (~> 0.10.6.0) java
```

**Comment by headius** [comment]
Ok I think this may just be a missed detail then. We will need to get a ruby-debug release that goes along with the ruby-debug-base 0.11.0 release.

I filed https://github.com/ruby-debug/ruby-debug/issues/31

**Comment by rdp** [comment]
This still fails with 9.2.11.0 FWIW...

**Comment by headius** [comment]
@rdp Yeah I'm not sure who can push a new ruby-debug gem. @enebo you worked more closely with these folks... what can we do?

**Comment by enebo** [comment]
@headius pinged @ViugiNick about releasing main gem as well.

**Comment by ViugiNick** [comment]
@enebo @headius done https://rubygems.org/gems/ruby-debug/versions/0.11.0

**Comment by enebo** [comment]
@ViugiNick great.  Thanks for that.  @rdp @Confusion  ^

**Comment by Confusion** [comment]
Verified it works. Thanks! :heart:

**Comment by headius** [comment]
Thank you @ViugiNick! Glad we can put this one to rest.

**Comment by amiracam** [comment]
what am I doing wrong , I can't load it:

C:\Users\Charles\IdeaProjects\DBIX2\src\main\jruby>bundle
Fetching gem metadata from https://rubygems.org/..........
Resolving dependencies...
Bundler could not find compatible versions for gem "ruby-debug-base":
  In Gemfile:
    ruby-debug (~> 0.11.0) java was resolved to 0.11.0, which depends on
      ruby-debug-base (~> 0.11.0.0) java

Could not find gem 'ruby-debug-base (~> 0.11.0.0)', which is required by gem
'ruby-debug (~> 0.11.0)', in any of the sources.

**Comment by amiracam** [comment]
I upgraded to jruby 9.2.11.0 i.e. had installed it about a week or so ago but not tested with it, I then tried bundler thru the IDEA and got the following interesting output:

C:\jruby-9.2.11.0\bin\jruby.exe C:\jruby-9.2.10.0-SNAPSHOT\bin\bundle install
2020-03-18T22:36:27.262-04:00 [main] WARN FilenoUtil : Native subprocess control requires open access to sun.nio.ch
Pass '--add-opens java.base/sun.nio.ch=org.jruby.dist' or '=org.jruby.core' to enable.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.jruby.ext.openssl.SecurityHelper (file:/C:/jruby-9.2.10.0-SNAPSHOT/lib/ruby/stdlib/jopenssl.jar) to constructor java.security.cert.CertificateFactory(java.security.cert.CertificateFactorySpi,java.security.Provider,java.lang.String)
WARNING: Please consider reporting this to the maintainers of org.jruby.ext.openssl.SecurityHelper
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Fetching gem metadata from https://rubygems.org/..........
Resolving dependencies...
?[31mBundler could not find compatible versions for gem "ruby-debug-base":
  In Gemfile:
    ruby-debug (~> 0.11.0) java was resolved to 0.11.0, which depends on
      ruby-debug-base (~> 0.11.0.0) java

Could not find gem 'ruby-debug-base (~> 0.11.0.0)', which is required by gem
'ruby-debug (~> 0.11.0)', in any of the sources.?[0m

Process finished with exit code 6

**Comment by amiracam** [comment]
sorry, some of the above may be because my local Java is set to 11, I'll check this out with Java 8 tomorrow

**Comment by headius** [comment]
@amiracam Yes, those warnings are harmless and we make improvements each release to reduce or eliminate them. There will be an updated jruby.exe soon.

**Comment by amiracam** [comment]
k, I'll wait till then to test my perhaps more complicated debugging scenarios I was having with IDEA the Vertx framework and Gradle in the mix, will this be a "public" release ? i.e. downloadable from your jruby.org ?

thanks

**Comment by headius** [comment]
@amiracam Yes, the next JRuby release (9.3) should have all the latest module tweaks plus an updated jruby.exe that applies them properly.
