### ISSUE TITLE
undefined method `new_ostruct_member' for No value for 'public' found

### ISSUE THREAD

**Issue by viglu** [jruby/jruby#7160]
Hi,

When upgrading from jruby 9.3.2.0 to 9.3.4.0 I get the follwoing error: message.

```
rvm use jruby-9.3.4.0
jruby -S bundle install
jruby -S bundle exec rake assets:clean
jruby -S bundle exec rake assets:precompile
jruby -S warble war
```
```
warble aborted!
NoMethodError: undefined method `new_ostruct_member' for No value for 'public' found
/usr/share/rvm/gems/jruby-9.3.4.0/gems/warbler-2.0.5/lib/warbler/traits/war.rb:200:in `method_missing'
/usr/share/rvm/gems/jruby-9.3.4.0/gems/warbler-2.0.5/lib/warbler/traits/war.rb:53:in `default_webxml_config'
/usr/share/rvm/gems/jruby-9.3.4.0/gems/warbler-2.0.5/lib/warbler/traits/war.rb:27:in `before_configure'
/usr/share/rvm/gems/jruby-9.3.4.0/gems/warbler-2.0.5/lib/warbler/traits.rb:29:in `block in before_configure'
/usr/share/rvm/gems/jruby-9.3.4.0/gems/warbler-2.0.5/lib/warbler/traits.rb:29:in `each'
/usr/share/rvm/gems/jruby-9.3.4.0/gems/warbler-2.0.5/lib/warbler/traits.rb:29:in `before_configure'
/usr/share/rvm/gems/jruby-9.3.4.0/gems/warbler-2.0.5/lib/warbler/config.rb:215:in `initialize'
config/warble.rb:19:in `new'
config/warble.rb:19:in `initialize'
/usr/share/rvm/gems/jruby-9.3.4.0/gems/warbler-2.0.5/lib/warbler/task.rb:46:in `eval'
/usr/share/rvm/gems/jruby-9.3.4.0/gems/warbler-2.0.5/lib/warbler/task.rb:46:in `initialize'
/usr/share/rvm/gems/jruby-9.3.4.0/gems/warbler-2.0.5/lib/warbler/application.rb:27:in `new'
/usr/share/rvm/gems/jruby-9.3.4.0/gems/warbler-2.0.5/lib/warbler/application.rb:27:in `load_rakefile'
/usr/share/rvm/gems/jruby-9.3.4.0/gems/warbler-2.0.5/lib/warbler/application.rb:79:in `run'
/usr/share/rvm/gems/jruby-9.3.4.0/gems/warbler-2.0.5/lib/warbler/application.rb:74:in `run'
/usr/share/rvm/gems/jruby-9.3.4.0/gems/warbler-2.0.5/bin/warble:11:in `<main>'
/usr/share/rvm/gems/jruby-9.3.4.0/bin/warble:25:in `load'
/usr/share/rvm/gems/jruby-9.3.4.0/bin/warble:25:in `<main>'
```

**Environment Information**
  
JRuby version: jruby 9.3.2.0 (2.6.8) 2021-12-01 0b8223f905 OpenJDK 64-Bit Server VM 17.0.2+8-Ubuntu-120.04 on 17.0.2+8-Ubuntu-120.04 +jit [linux-x86_64]
System: Ubuntu 20.04: Linux my-machine 5.4.0-105-generic #119-Ubuntu SMP Mon Mar 7 18:49:24 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

```
GEM file:
GEM
  remote: https://rubygems.org/
  specs:
    actioncable (6.1.4.6)
      actionpack (= 6.1.4.6)
      activesupport (= 6.1.4.6)
      nio4r (~> 2.0)
      websocket-driver (>= 0.6.1)
    actionmailbox (6.1.4.6)
      actionpack (= 6.1.4.6)
      activejob (= 6.1.4.6)
      activerecord (= 6.1.4.6)
      activestorage (= 6.1.4.6)
      activesupport (= 6.1.4.6)
      mail (>= 2.7.1)
    actionmailer (6.1.4.6)
      actionpack (= 6.1.4.6)
      actionview (= 6.1.4.6)
      activejob (= 6.1.4.6)
      activesupport (= 6.1.4.6)
      mail (~> 2.5, >= 2.5.4)
      rails-dom-testing (~> 2.0)
    actionpack (6.1.4.6)
      actionview (= 6.1.4.6)
      activesupport (= 6.1.4.6)
      rack (~> 2.0, >= 2.0.9)
      rack-test (>= 0.6.3)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.0, >= 1.2.0)
    actiontext (6.1.4.6)
      actionpack (= 6.1.4.6)
      activerecord (= 6.1.4.6)
      activestorage (= 6.1.4.6)
      activesupport (= 6.1.4.6)
      nokogiri (>= 1.8.5)
    actionview (6.1.4.6)
      activesupport (= 6.1.4.6)
      builder (~> 3.1)
      erubi (~> 1.4)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.1, >= 1.2.0)
    activejob (6.1.4.6)
      activesupport (= 6.1.4.6)
      globalid (>= 0.3.6)
    activemodel (6.1.4.6)
      activesupport (= 6.1.4.6)
    activerecord (6.1.4.6)
      activemodel (= 6.1.4.6)
      activesupport (= 6.1.4.6)
    activerecord-jdbc-adapter (61.1-java)
      activerecord (~> 6.1.0)
    activerecord-jdbcmysql-adapter (61.1-java)
      activerecord-jdbc-adapter (= 61.1)
      jdbc-mysql (>= 5.1.36, < 9)
    activestorage (6.1.4.6)
      actionpack (= 6.1.4.6)
      activejob (= 6.1.4.6)
      activerecord (= 6.1.4.6)
      activesupport (= 6.1.4.6)
      marcel (~> 1.0.0)
      mini_mime (>= 1.1.0)
    activesupport (6.1.4.6)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      i18n (>= 1.6, < 2)
      minitest (>= 5.1)
      tzinfo (~> 2.0)
      zeitwerk (~> 2.3)
    addressable (2.8.0)
      public_suffix (>= 2.0.2, < 5.0)
    ansi-to-html (0.0.3)
    awesome_nested_set (3.5.0)
      activerecord (>= 4.0.0, < 7.1)
    bcrypt (3.1.16-java)
    builder (3.2.4)
    capybara (3.36.0)
      addressable
      matrix
      mini_mime (>= 0.1.3)
      nokogiri (~> 1.8)
      rack (>= 1.6.0)
      rack-test (>= 0.6.3)
      regexp_parser (>= 1.5, < 3.0)
      xpath (~> 3.2)
    childprocess (4.1.0)
    concurrent-ruby (1.1.9)
    crass (1.0.6)
    devise (4.8.1)
      bcrypt (~> 3.0)
      orm_adapter (~> 0.1)
      railties (>= 4.1.0)
      responders
      warden (~> 1.2.3)
    devise-encryptable (0.2.0)
      devise (>= 2.1.0)
    domain_name (0.5.20190701)
      unf (>= 0.0.5, < 1.0.0)
    erubi (1.10.0)
    globalid (1.0.0)
      activesupport (>= 5.0)
    http-accept (1.7.0)
    http-cookie (1.0.4)
      domain_name (~> 0.5)
    i18n (1.10.0)
      concurrent-ruby (~> 1.0)
    jbuilder (2.11.5)
      actionview (>= 5.0.0)
      activesupport (>= 5.0.0)
    jdbc-mysql (8.0.27)
    jquery-rails (4.4.0)
      rails-dom-testing (>= 1, < 3)
      railties (>= 4.2.0)
      thor (>= 0.14, < 2.0)
    loofah (2.14.0)
      crass (~> 1.0.2)
      nokogiri (>= 1.5.9)
    mail (2.7.1)
      mini_mime (>= 0.1.1)
    marcel (1.0.2)
    matrix (0.4.2)
    method_source (1.0.0)
    mime-types (3.4.1)
      mime-types-data (~> 3.2015)
    mime-types-data (3.2022.0105)
    mini_mime (1.1.2)
    minitest (5.15.0)
    netrc (0.11.0)
    nio4r (2.5.8-java)
    nokogiri (1.13.1-java)
      racc (~> 1.4)
    orm_adapter (0.5.0)
    public_suffix (4.0.6)
    puma (5.6.2-java)
      nio4r (~> 2.0)
    racc (1.6.0-java)
    rack (2.2.3)
    rack-mini-profiler (2.3.3)
      rack (>= 1.2.0)
    rack-proxy (0.7.2)
      rack
    rack-test (1.1.0)
      rack (>= 1.0, < 3)
    rails (6.1.4.6)
      actioncable (= 6.1.4.6)
      actionmailbox (= 6.1.4.6)
      actionmailer (= 6.1.4.6)
      actionpack (= 6.1.4.6)
      actiontext (= 6.1.4.6)
      actionview (= 6.1.4.6)
      activejob (= 6.1.4.6)
      activemodel (= 6.1.4.6)
      activerecord (= 6.1.4.6)
      activestorage (= 6.1.4.6)
      activesupport (= 6.1.4.6)
      bundler (>= 1.15.0)
      railties (= 6.1.4.6)
      sprockets-rails (>= 2.0.0)
    rails-dom-testing (2.0.3)
      activesupport (>= 4.2.0)
      nokogiri (>= 1.6)
    rails-html-sanitizer (1.4.2)
      loofah (~> 2.3)
    railties (6.1.4.6)
      actionpack (= 6.1.4.6)
      activesupport (= 6.1.4.6)
      method_source
      rake (>= 0.13)
      thor (~> 1.0)
    rake (13.0.6)
    regexp_parser (2.2.1)
    responders (3.0.1)
      actionpack (>= 5.0)
      railties (>= 5.0)
    rest-client (2.1.0)
      http-accept (>= 1.7.0, < 2.0)
      http-cookie (>= 1.0.2, < 2.0)
      mime-types (>= 1.16, < 4.0)
      netrc (~> 0.8)
    rexml (3.2.5)
    rubyzip (1.3.0)
    selenium-webdriver (4.1.0)
      childprocess (>= 0.5, < 5.0)
      rexml (~> 3.2, >= 3.2.5)
      rubyzip (>= 1.2.2)
    semantic_range (3.0.0)
    sprockets (4.0.2)
      concurrent-ruby (~> 1.0)
      rack (> 1, < 3)
    sprockets-rails (3.4.2)
      actionpack (>= 5.2)
      activesupport (>= 5.2)
      sprockets (>= 3.0.0)
    thor (1.2.1)
    turbolinks (5.2.1)
      turbolinks-source (~> 5.2)
    turbolinks-source (5.2.0)
    tzinfo (2.0.4)
      concurrent-ruby (~> 1.0)
    tzinfo-data (1.2021.5)
      tzinfo (>= 1.0.0)
    unf (0.1.4-java)
    warden (1.2.9)
      rack (>= 2.0.9)
    webdrivers (5.0.0)
      nokogiri (~> 1.6)
      rubyzip (>= 1.3.0)
      selenium-webdriver (~> 4.0)
    webpacker (5.4.3)
      activesupport (>= 5.2)
      rack-proxy (>= 0.6.1)
      railties (>= 5.2)
      semantic_range (>= 2.3.0)
    websocket-driver (0.7.5-java)
      websocket-extensions (>= 0.1.0)
    websocket-extensions (0.1.5)
    will_paginate (3.3.1)
    xpath (3.2.0)
      nokogiri (~> 1.8)
    zeitwerk (2.5.4)

PLATFORMS
  universal-java-1.8
  universal-java-17

DEPENDENCIES
  activerecord-jdbcmysql-adapter
  ansi-to-html
  awesome_nested_set
  capybara (>= 3.26)
  devise
  devise-encryptable
  jbuilder (~> 2.7)
  jquery-rails
  puma (~> 5.0)
  rack-mini-profiler (~> 2.0)
  rails (~> 6.1.4, >= 6.1.4.4)
  rest-client
  selenium-webdriver
  turbolinks (~> 5)
  tzinfo-data
  webdrivers
  webpacker (~> 5.0)
  will_paginate (~> 3.0)

RUBY VERSION
   ruby 2.6.8p0 (jruby 9.3.2.0)

BUNDLED WITH
   2.2.29
```

**Comment by headius** [comment]
This may be an incompatibility between warbler and the newer versions of ostruct.

@marcandre Could the eager aliasing of all those methods be causing a method_missing in another library to fail?

**Comment by marcandre** [comment]
Mmm, I have no idea, I'm not sure I even understand the error message... What does "NoMethodError: undefined method `new_ostruct_member' for No value for 'public' found" mean? It's like there's some kind of object with string representation "No value for 'public' found"? And why is `new_ostruct_member` called on it?

I'm currently traveling, so not much time to investigate...

**Comment by JesseChavez** [comment]
I've see this issue as well when I tried to upgrade my apps to JRuby `9.3.4.0`

**Comment by JesseChavez** [comment]
Hi @headius,

I tracked down the issue and I submitted a PR in the warbler repo
https://github.com/jruby/warbler/pull/513

**Comment by viglu** [comment]
Some knows when the next warble release is planned with this bug fix? Or is there a workaround ?

**Comment by rootcfg** [comment]
jruby-9.4.0.0 / warbler-2.0.5 The same problem


cab-wsm-0075083:cats dolgashov-ds$ jruby -S warble war
warble aborted!
NoMethodError: undefined method `new_ostruct_member' for No value for 'public' found
/Users/dolgashov-ds/.rvm/gems/jruby-9.4.0.0/gems/warbler-2.0.5/lib/warbler/traits/war.rb:200:in `method_missing'
/Users/dolgashov-ds/.rvm/gems/jruby-9.4.0.0/gems/warbler-2.0.5/lib/warbler/traits/war.rb:53:in `default_webxml_config'
/Users/dolgashov-ds/.rvm/gems/jruby-9.4.0.0/gems/warbler-2.0.5/lib/warbler/traits/war.rb:27:in `before_configure'
/Users/dolgashov-ds/.rvm/gems/jruby-9.4.0.0/gems/warbler-2.0.5/lib/warbler/traits.rb:29:in `block in before_configure'
/Users/dolgashov-ds/.rvm/gems/jruby-9.4.0.0/gems/warbler-2.0.5/lib/warbler/traits.rb:29:in `each'
/Users/dolgashov-ds/.rvm/gems/jruby-9.4.0.0/gems/warbler-2.0.5/lib/warbler/traits.rb:29:in `before_configure'
/Users/dolgashov-ds/.rvm/gems/jruby-9.4.0.0/gems/warbler-2.0.5/lib/warbler/config.rb:215:in `initialize'
/Users/dolgashov-ds/.rvm/gems/jruby-9.4.0.0/gems/warbler-2.0.5/lib/warbler/task.rb:48:in `new'
/Users/dolgashov-ds/.rvm/gems/jruby-9.4.0.0/gems/warbler-2.0.5/lib/warbler/task.rb:48:in `initialize'
/Users/dolgashov-ds/.rvm/gems/jruby-9.4.0.0/gems/warbler-2.0.5/lib/warbler/application.rb:27:in `new'
/Users/dolgashov-ds/.rvm/gems/jruby-9.4.0.0/gems/warbler-2.0.5/lib/warbler/application.rb:27:in `load_rakefile'
/Users/dolgashov-ds/.rvm/gems/jruby-9.4.0.0/gems/warbler-2.0.5/lib/warbler/application.rb:79:in `run'
/Users/dolgashov-ds/.rvm/gems/jruby-9.4.0.0/gems/warbler-2.0.5/lib/warbler/application.rb:74:in `run'
/Users/dolgashov-ds/.rvm/gems/jruby-9.4.0.0/gems/warbler-2.0.5/bin/warble:11:in `<main>'
/Users/dolgashov-ds/.rvm/gems/jruby-9.4.0.0/bin/warble:25:in `load'
/Users/dolgashov-ds/.rvm/gems/jruby-9.4.0.0/bin/warble:25:in `<main>'
(See full trace by running task with --trace)
cab-wsm-0075083:cats dolgashov-ds$

**Comment by keeguon** [comment]
@rootcfg I concur I was doing build test against 9.4.0.0 this morning and it failed miserably.

**Comment by rootcfg** [comment]
@keeguon I'm upset. My tech stack is WildFly and I can't use pure ruby due to security policies. Apparently, we can only wait.

**Comment by JesseChavez** [comment]
This issue is due warbler not compatible with the latest open struct.

The issue is fixed in warbler master but there is not release yet in the meantime you can try

```
gem 'warbler', github: 'jruby/warbler'
```

**Comment by headius** [comment]
We will try to get a release out soon!

**Comment by yosepkim** [comment]
I am still running into this issue.

warbler-2.0.5
jruby-9.4.12.0

**Comment by chadlwilson** [comment]
This was eventually fixed with proper release of warbler 2.1.0 in https://github.com/jruby/warbler/releases/tag/v2.1.0 Not a jruby issue.
